// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MonsterCfg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DongciDaci {

  /// <summary>Holder for reflection information generated from MonsterCfg.proto</summary>
  public static partial class MonsterCfgReflection {

    #region Descriptor
    /// <summary>File descriptor for MonsterCfg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MonsterCfgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBNb25zdGVyQ2ZnLnByb3RvEgpEb25nY2lEYWNpItkCCg5Nb25zdGVyQmFz",
            "ZUNmZxIKCgJJRBgBIAEoDRIMCgROYW1lGAIgASgJEhAKCE5pY2tOYW1lGAMg",
            "ASgJEg4KBlByZWZhYhgEIAEoCRINCgVTcGVlZBgFIAEoAhIUCgxEYXNoRGlz",
            "dGFuY2UYBiABKAISFQoNQmVoYXZpb3VyVHJlZRgHIAEoCRIUCgxBdHRhY2tS",
            "YWRpdXMYCCABKAISFgoOSW50ZXJhY3RSYWRpdXMYCSABKAISFAoMRm9sbG93",
            "UmFkaXVzGAogASgCEg0KBU1heEhwGAsgASgFEhIKCkJhc2VBdHRhY2sYDCAB",
            "KAUSEwoLRGVmZW5zZVJhdGUYDSABKAISFAoMQ3JpdGljYWxSYXRlGA4gASgC",
            "EhcKD0NyaXRpY2FsRG1nUmF0ZRgPIAEoAhIRCglEb2RnZVJhdGUYECABKAIS",
            "EQoJTW92ZVNwZWVkGBEgASgCIr0BCg9Nb25zdGVyQ2ZnX0RhdGESUgoUTW9u",
            "c3RlckJhc2VDZmdfaXRlbXMYASADKAsyNC5Eb25nY2lEYWNpLk1vbnN0ZXJD",
            "ZmdfRGF0YS5Nb25zdGVyQmFzZUNmZ0l0ZW1zRW50cnkaVgoYTW9uc3RlckJh",
            "c2VDZmdJdGVtc0VudHJ5EgsKA2tleRgBIAEoDRIpCgV2YWx1ZRgCIAEoCzIa",
            "LkRvbmdjaURhY2kuTW9uc3RlckJhc2VDZmc6AjgBQiMKIWNvbS50cmluaXRp",
            "Z2FtZXMuc2VydmVyLmNvbmYuYXV0b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DongciDaci.MonsterBaseCfg), global::DongciDaci.MonsterBaseCfg.Parser, new[]{ "ID", "Name", "NickName", "Prefab", "Speed", "DashDistance", "BehaviourTree", "AttackRadius", "InteractRadius", "FollowRadius", "MaxHp", "BaseAttack", "DefenseRate", "CriticalRate", "CriticalDmgRate", "DodgeRate", "MoveSpeed" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DongciDaci.MonsterCfg_Data), global::DongciDaci.MonsterCfg_Data.Parser, new[]{ "MonsterBaseCfgItems" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MonsterBaseCfg : pb::IMessage<MonsterBaseCfg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonsterBaseCfg> _parser = new pb::MessageParser<MonsterBaseCfg>(() => new MonsterBaseCfg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonsterBaseCfg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DongciDaci.MonsterCfgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterBaseCfg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterBaseCfg(MonsterBaseCfg other) : this() {
      iD_ = other.iD_;
      name_ = other.name_;
      nickName_ = other.nickName_;
      prefab_ = other.prefab_;
      speed_ = other.speed_;
      dashDistance_ = other.dashDistance_;
      behaviourTree_ = other.behaviourTree_;
      attackRadius_ = other.attackRadius_;
      interactRadius_ = other.interactRadius_;
      followRadius_ = other.followRadius_;
      maxHp_ = other.maxHp_;
      baseAttack_ = other.baseAttack_;
      defenseRate_ = other.defenseRate_;
      criticalRate_ = other.criticalRate_;
      criticalDmgRate_ = other.criticalDmgRate_;
      dodgeRate_ = other.dodgeRate_;
      moveSpeed_ = other.moveSpeed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterBaseCfg Clone() {
      return new MonsterBaseCfg(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private uint iD_;
    /// <summary>
    ///* ID 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    ///* 名称 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NickName" field.</summary>
    public const int NickNameFieldNumber = 3;
    private string nickName_ = "";
    /// <summary>
    ///* 英文名称 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NickName {
      get { return nickName_; }
      set {
        nickName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Prefab" field.</summary>
    public const int PrefabFieldNumber = 4;
    private string prefab_ = "";
    /// <summary>
    ///* 预制体路径 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Prefab {
      get { return prefab_; }
      set {
        prefab_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Speed" field.</summary>
    public const int SpeedFieldNumber = 5;
    private float speed_;
    /// <summary>
    ///* 角色的移动速度 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "DashDistance" field.</summary>
    public const int DashDistanceFieldNumber = 6;
    private float dashDistance_;
    /// <summary>
    ///* 角色的冲刺距离 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DashDistance {
      get { return dashDistance_; }
      set {
        dashDistance_ = value;
      }
    }

    /// <summary>Field number for the "BehaviourTree" field.</summary>
    public const int BehaviourTreeFieldNumber = 7;
    private string behaviourTree_ = "";
    /// <summary>
    ///* 行为树名称 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BehaviourTree {
      get { return behaviourTree_; }
      set {
        behaviourTree_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AttackRadius" field.</summary>
    public const int AttackRadiusFieldNumber = 8;
    private float attackRadius_;
    /// <summary>
    ///* 攻击半径 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AttackRadius {
      get { return attackRadius_; }
      set {
        attackRadius_ = value;
      }
    }

    /// <summary>Field number for the "InteractRadius" field.</summary>
    public const int InteractRadiusFieldNumber = 9;
    private float interactRadius_;
    /// <summary>
    ///* 交互半径 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float InteractRadius {
      get { return interactRadius_; }
      set {
        interactRadius_ = value;
      }
    }

    /// <summary>Field number for the "FollowRadius" field.</summary>
    public const int FollowRadiusFieldNumber = 10;
    private float followRadius_;
    /// <summary>
    ///* 跟随半径 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float FollowRadius {
      get { return followRadius_; }
      set {
        followRadius_ = value;
      }
    }

    /// <summary>Field number for the "MaxHp" field.</summary>
    public const int MaxHpFieldNumber = 11;
    private int maxHp_;
    /// <summary>
    ///* 最大生命 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxHp {
      get { return maxHp_; }
      set {
        maxHp_ = value;
      }
    }

    /// <summary>Field number for the "BaseAttack" field.</summary>
    public const int BaseAttackFieldNumber = 12;
    private int baseAttack_;
    /// <summary>
    ///* 基础攻击值 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BaseAttack {
      get { return baseAttack_; }
      set {
        baseAttack_ = value;
      }
    }

    /// <summary>Field number for the "DefenseRate" field.</summary>
    public const int DefenseRateFieldNumber = 13;
    private float defenseRate_;
    /// <summary>
    ///* 伤害减免系数 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DefenseRate {
      get { return defenseRate_; }
      set {
        defenseRate_ = value;
      }
    }

    /// <summary>Field number for the "CriticalRate" field.</summary>
    public const int CriticalRateFieldNumber = 14;
    private float criticalRate_;
    /// <summary>
    ///* 暴击率 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float CriticalRate {
      get { return criticalRate_; }
      set {
        criticalRate_ = value;
      }
    }

    /// <summary>Field number for the "CriticalDmgRate" field.</summary>
    public const int CriticalDmgRateFieldNumber = 15;
    private float criticalDmgRate_;
    /// <summary>
    ///* 暴击伤害 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float CriticalDmgRate {
      get { return criticalDmgRate_; }
      set {
        criticalDmgRate_ = value;
      }
    }

    /// <summary>Field number for the "DodgeRate" field.</summary>
    public const int DodgeRateFieldNumber = 16;
    private float dodgeRate_;
    /// <summary>
    ///* 闪避率 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DodgeRate {
      get { return dodgeRate_; }
      set {
        dodgeRate_ = value;
      }
    }

    /// <summary>Field number for the "MoveSpeed" field.</summary>
    public const int MoveSpeedFieldNumber = 17;
    private float moveSpeed_;
    /// <summary>
    ///* 移动速度 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MoveSpeed {
      get { return moveSpeed_; }
      set {
        moveSpeed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonsterBaseCfg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonsterBaseCfg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if (Name != other.Name) return false;
      if (NickName != other.NickName) return false;
      if (Prefab != other.Prefab) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Speed, other.Speed)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DashDistance, other.DashDistance)) return false;
      if (BehaviourTree != other.BehaviourTree) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AttackRadius, other.AttackRadius)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(InteractRadius, other.InteractRadius)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FollowRadius, other.FollowRadius)) return false;
      if (MaxHp != other.MaxHp) return false;
      if (BaseAttack != other.BaseAttack) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DefenseRate, other.DefenseRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CriticalRate, other.CriticalRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CriticalDmgRate, other.CriticalDmgRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DodgeRate, other.DodgeRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MoveSpeed, other.MoveSpeed)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ID != 0) hash ^= ID.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (NickName.Length != 0) hash ^= NickName.GetHashCode();
      if (Prefab.Length != 0) hash ^= Prefab.GetHashCode();
      if (Speed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Speed);
      if (DashDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DashDistance);
      if (BehaviourTree.Length != 0) hash ^= BehaviourTree.GetHashCode();
      if (AttackRadius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AttackRadius);
      if (InteractRadius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(InteractRadius);
      if (FollowRadius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FollowRadius);
      if (MaxHp != 0) hash ^= MaxHp.GetHashCode();
      if (BaseAttack != 0) hash ^= BaseAttack.GetHashCode();
      if (DefenseRate != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DefenseRate);
      if (CriticalRate != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CriticalRate);
      if (CriticalDmgRate != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CriticalDmgRate);
      if (DodgeRate != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DodgeRate);
      if (MoveSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MoveSpeed);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ID);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (NickName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NickName);
      }
      if (Prefab.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Prefab);
      }
      if (Speed != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Speed);
      }
      if (DashDistance != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(DashDistance);
      }
      if (BehaviourTree.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(BehaviourTree);
      }
      if (AttackRadius != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(AttackRadius);
      }
      if (InteractRadius != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(InteractRadius);
      }
      if (FollowRadius != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(FollowRadius);
      }
      if (MaxHp != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(MaxHp);
      }
      if (BaseAttack != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(BaseAttack);
      }
      if (DefenseRate != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(DefenseRate);
      }
      if (CriticalRate != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(CriticalRate);
      }
      if (CriticalDmgRate != 0F) {
        output.WriteRawTag(125);
        output.WriteFloat(CriticalDmgRate);
      }
      if (DodgeRate != 0F) {
        output.WriteRawTag(133, 1);
        output.WriteFloat(DodgeRate);
      }
      if (MoveSpeed != 0F) {
        output.WriteRawTag(141, 1);
        output.WriteFloat(MoveSpeed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ID);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (NickName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NickName);
      }
      if (Prefab.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Prefab);
      }
      if (Speed != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Speed);
      }
      if (DashDistance != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(DashDistance);
      }
      if (BehaviourTree.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(BehaviourTree);
      }
      if (AttackRadius != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(AttackRadius);
      }
      if (InteractRadius != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(InteractRadius);
      }
      if (FollowRadius != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(FollowRadius);
      }
      if (MaxHp != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(MaxHp);
      }
      if (BaseAttack != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(BaseAttack);
      }
      if (DefenseRate != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(DefenseRate);
      }
      if (CriticalRate != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(CriticalRate);
      }
      if (CriticalDmgRate != 0F) {
        output.WriteRawTag(125);
        output.WriteFloat(CriticalDmgRate);
      }
      if (DodgeRate != 0F) {
        output.WriteRawTag(133, 1);
        output.WriteFloat(DodgeRate);
      }
      if (MoveSpeed != 0F) {
        output.WriteRawTag(141, 1);
        output.WriteFloat(MoveSpeed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ID);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (NickName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NickName);
      }
      if (Prefab.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prefab);
      }
      if (Speed != 0F) {
        size += 1 + 4;
      }
      if (DashDistance != 0F) {
        size += 1 + 4;
      }
      if (BehaviourTree.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BehaviourTree);
      }
      if (AttackRadius != 0F) {
        size += 1 + 4;
      }
      if (InteractRadius != 0F) {
        size += 1 + 4;
      }
      if (FollowRadius != 0F) {
        size += 1 + 4;
      }
      if (MaxHp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxHp);
      }
      if (BaseAttack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BaseAttack);
      }
      if (DefenseRate != 0F) {
        size += 1 + 4;
      }
      if (CriticalRate != 0F) {
        size += 1 + 4;
      }
      if (CriticalDmgRate != 0F) {
        size += 1 + 4;
      }
      if (DodgeRate != 0F) {
        size += 2 + 4;
      }
      if (MoveSpeed != 0F) {
        size += 2 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonsterBaseCfg other) {
      if (other == null) {
        return;
      }
      if (other.ID != 0) {
        ID = other.ID;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.NickName.Length != 0) {
        NickName = other.NickName;
      }
      if (other.Prefab.Length != 0) {
        Prefab = other.Prefab;
      }
      if (other.Speed != 0F) {
        Speed = other.Speed;
      }
      if (other.DashDistance != 0F) {
        DashDistance = other.DashDistance;
      }
      if (other.BehaviourTree.Length != 0) {
        BehaviourTree = other.BehaviourTree;
      }
      if (other.AttackRadius != 0F) {
        AttackRadius = other.AttackRadius;
      }
      if (other.InteractRadius != 0F) {
        InteractRadius = other.InteractRadius;
      }
      if (other.FollowRadius != 0F) {
        FollowRadius = other.FollowRadius;
      }
      if (other.MaxHp != 0) {
        MaxHp = other.MaxHp;
      }
      if (other.BaseAttack != 0) {
        BaseAttack = other.BaseAttack;
      }
      if (other.DefenseRate != 0F) {
        DefenseRate = other.DefenseRate;
      }
      if (other.CriticalRate != 0F) {
        CriticalRate = other.CriticalRate;
      }
      if (other.CriticalDmgRate != 0F) {
        CriticalDmgRate = other.CriticalDmgRate;
      }
      if (other.DodgeRate != 0F) {
        DodgeRate = other.DodgeRate;
      }
      if (other.MoveSpeed != 0F) {
        MoveSpeed = other.MoveSpeed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            NickName = input.ReadString();
            break;
          }
          case 34: {
            Prefab = input.ReadString();
            break;
          }
          case 45: {
            Speed = input.ReadFloat();
            break;
          }
          case 53: {
            DashDistance = input.ReadFloat();
            break;
          }
          case 58: {
            BehaviourTree = input.ReadString();
            break;
          }
          case 69: {
            AttackRadius = input.ReadFloat();
            break;
          }
          case 77: {
            InteractRadius = input.ReadFloat();
            break;
          }
          case 85: {
            FollowRadius = input.ReadFloat();
            break;
          }
          case 88: {
            MaxHp = input.ReadInt32();
            break;
          }
          case 96: {
            BaseAttack = input.ReadInt32();
            break;
          }
          case 109: {
            DefenseRate = input.ReadFloat();
            break;
          }
          case 117: {
            CriticalRate = input.ReadFloat();
            break;
          }
          case 125: {
            CriticalDmgRate = input.ReadFloat();
            break;
          }
          case 133: {
            DodgeRate = input.ReadFloat();
            break;
          }
          case 141: {
            MoveSpeed = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ID = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            NickName = input.ReadString();
            break;
          }
          case 34: {
            Prefab = input.ReadString();
            break;
          }
          case 45: {
            Speed = input.ReadFloat();
            break;
          }
          case 53: {
            DashDistance = input.ReadFloat();
            break;
          }
          case 58: {
            BehaviourTree = input.ReadString();
            break;
          }
          case 69: {
            AttackRadius = input.ReadFloat();
            break;
          }
          case 77: {
            InteractRadius = input.ReadFloat();
            break;
          }
          case 85: {
            FollowRadius = input.ReadFloat();
            break;
          }
          case 88: {
            MaxHp = input.ReadInt32();
            break;
          }
          case 96: {
            BaseAttack = input.ReadInt32();
            break;
          }
          case 109: {
            DefenseRate = input.ReadFloat();
            break;
          }
          case 117: {
            CriticalRate = input.ReadFloat();
            break;
          }
          case 125: {
            CriticalDmgRate = input.ReadFloat();
            break;
          }
          case 133: {
            DodgeRate = input.ReadFloat();
            break;
          }
          case 141: {
            MoveSpeed = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MonsterCfg_Data : pb::IMessage<MonsterCfg_Data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonsterCfg_Data> _parser = new pb::MessageParser<MonsterCfg_Data>(() => new MonsterCfg_Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonsterCfg_Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DongciDaci.MonsterCfgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterCfg_Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterCfg_Data(MonsterCfg_Data other) : this() {
      monsterBaseCfgItems_ = other.monsterBaseCfgItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterCfg_Data Clone() {
      return new MonsterCfg_Data(this);
    }

    /// <summary>Field number for the "MonsterBaseCfg_items" field.</summary>
    public const int MonsterBaseCfgItemsFieldNumber = 1;
    private static readonly pbc::MapField<uint, global::DongciDaci.MonsterBaseCfg>.Codec _map_monsterBaseCfgItems_codec
        = new pbc::MapField<uint, global::DongciDaci.MonsterBaseCfg>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForMessage(18, global::DongciDaci.MonsterBaseCfg.Parser), 10);
    private readonly pbc::MapField<uint, global::DongciDaci.MonsterBaseCfg> monsterBaseCfgItems_ = new pbc::MapField<uint, global::DongciDaci.MonsterBaseCfg>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, global::DongciDaci.MonsterBaseCfg> MonsterBaseCfgItems {
      get { return monsterBaseCfgItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonsterCfg_Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonsterCfg_Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!MonsterBaseCfgItems.Equals(other.MonsterBaseCfgItems)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= MonsterBaseCfgItems.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      monsterBaseCfgItems_.WriteTo(output, _map_monsterBaseCfgItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      monsterBaseCfgItems_.WriteTo(ref output, _map_monsterBaseCfgItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += monsterBaseCfgItems_.CalculateSize(_map_monsterBaseCfgItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonsterCfg_Data other) {
      if (other == null) {
        return;
      }
      monsterBaseCfgItems_.MergeFrom(other.monsterBaseCfgItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            monsterBaseCfgItems_.AddEntriesFrom(input, _map_monsterBaseCfgItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            monsterBaseCfgItems_.AddEntriesFrom(ref input, _map_monsterBaseCfgItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
