// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SkillEffectCfg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DongciDaci {

  /// <summary>Holder for reflection information generated from SkillEffectCfg.proto</summary>
  public static partial class SkillEffectCfgReflection {

    #region Descriptor
    /// <summary>File descriptor for SkillEffectCfg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SkillEffectCfgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRTa2lsbEVmZmVjdENmZy5wcm90bxIKRG9uZ2NpRGFjaSKvAQoMU2tFZnRC",
            "YXNlQ2ZnEgoKAklEGAEgASgNEg4KBkNoTmFtZRgCIAEoCRIOCgZFbk5hbWUY",
            "AyABKAkSEQoJQ2xhc3NOYW1lGAQgASgJEhEKCUNoRGVzY3JpcBgFIAEoCRIR",
            "CglFbkRlc2NyaXAYBiABKAkSEAoISWNvblBhdGgYByABKAkSFQoNVkZYUHJl",
            "ZmFiUGF0aBgIIAEoCRIRCglBdWRpb1BhdGgYCSABKAkivQEKE1NraWxsRWZm",
            "ZWN0Q2ZnX0RhdGESUgoSU2tFZnRCYXNlQ2ZnX2l0ZW1zGAEgAygLMjYuRG9u",
            "Z2NpRGFjaS5Ta2lsbEVmZmVjdENmZ19EYXRhLlNrRWZ0QmFzZUNmZ0l0ZW1z",
            "RW50cnkaUgoWU2tFZnRCYXNlQ2ZnSXRlbXNFbnRyeRILCgNrZXkYASABKA0S",
            "JwoFdmFsdWUYAiABKAsyGC5Eb25nY2lEYWNpLlNrRWZ0QmFzZUNmZzoCOAFC",
            "IwohY29tLnRyaW5pdGlnYW1lcy5zZXJ2ZXIuY29uZi5hdXRvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DongciDaci.SkEftBaseCfg), global::DongciDaci.SkEftBaseCfg.Parser, new[]{ "ID", "ChName", "EnName", "ClassName", "ChDescrip", "EnDescrip", "IconPath", "VFXPrefabPath", "AudioPath" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DongciDaci.SkillEffectCfg_Data), global::DongciDaci.SkillEffectCfg_Data.Parser, new[]{ "SkEftBaseCfgItems" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SkEftBaseCfg : pb::IMessage<SkEftBaseCfg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SkEftBaseCfg> _parser = new pb::MessageParser<SkEftBaseCfg>(() => new SkEftBaseCfg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SkEftBaseCfg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DongciDaci.SkillEffectCfgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkEftBaseCfg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkEftBaseCfg(SkEftBaseCfg other) : this() {
      iD_ = other.iD_;
      chName_ = other.chName_;
      enName_ = other.enName_;
      className_ = other.className_;
      chDescrip_ = other.chDescrip_;
      enDescrip_ = other.enDescrip_;
      iconPath_ = other.iconPath_;
      vFXPrefabPath_ = other.vFXPrefabPath_;
      audioPath_ = other.audioPath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkEftBaseCfg Clone() {
      return new SkEftBaseCfg(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private uint iD_;
    /// <summary>
    ///* ID 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "ChName" field.</summary>
    public const int ChNameFieldNumber = 2;
    private string chName_ = "";
    /// <summary>
    ///* 中文名称 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChName {
      get { return chName_; }
      set {
        chName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EnName" field.</summary>
    public const int EnNameFieldNumber = 3;
    private string enName_ = "";
    /// <summary>
    ///* 英文名称 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EnName {
      get { return enName_; }
      set {
        enName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ClassName" field.</summary>
    public const int ClassNameFieldNumber = 4;
    private string className_ = "";
    /// <summary>
    ///* 类名 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClassName {
      get { return className_; }
      set {
        className_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ChDescrip" field.</summary>
    public const int ChDescripFieldNumber = 5;
    private string chDescrip_ = "";
    /// <summary>
    ///* 中文描述 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChDescrip {
      get { return chDescrip_; }
      set {
        chDescrip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EnDescrip" field.</summary>
    public const int EnDescripFieldNumber = 6;
    private string enDescrip_ = "";
    /// <summary>
    ///* 英文描述 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EnDescrip {
      get { return enDescrip_; }
      set {
        enDescrip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IconPath" field.</summary>
    public const int IconPathFieldNumber = 7;
    private string iconPath_ = "";
    /// <summary>
    ///* 图标路径 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IconPath {
      get { return iconPath_; }
      set {
        iconPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "VFXPrefabPath" field.</summary>
    public const int VFXPrefabPathFieldNumber = 8;
    private string vFXPrefabPath_ = "";
    /// <summary>
    ///* 特效路径 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VFXPrefabPath {
      get { return vFXPrefabPath_; }
      set {
        vFXPrefabPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AudioPath" field.</summary>
    public const int AudioPathFieldNumber = 9;
    private string audioPath_ = "";
    /// <summary>
    ///* 音频路径 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AudioPath {
      get { return audioPath_; }
      set {
        audioPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SkEftBaseCfg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SkEftBaseCfg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if (ChName != other.ChName) return false;
      if (EnName != other.EnName) return false;
      if (ClassName != other.ClassName) return false;
      if (ChDescrip != other.ChDescrip) return false;
      if (EnDescrip != other.EnDescrip) return false;
      if (IconPath != other.IconPath) return false;
      if (VFXPrefabPath != other.VFXPrefabPath) return false;
      if (AudioPath != other.AudioPath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ID != 0) hash ^= ID.GetHashCode();
      if (ChName.Length != 0) hash ^= ChName.GetHashCode();
      if (EnName.Length != 0) hash ^= EnName.GetHashCode();
      if (ClassName.Length != 0) hash ^= ClassName.GetHashCode();
      if (ChDescrip.Length != 0) hash ^= ChDescrip.GetHashCode();
      if (EnDescrip.Length != 0) hash ^= EnDescrip.GetHashCode();
      if (IconPath.Length != 0) hash ^= IconPath.GetHashCode();
      if (VFXPrefabPath.Length != 0) hash ^= VFXPrefabPath.GetHashCode();
      if (AudioPath.Length != 0) hash ^= AudioPath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ID);
      }
      if (ChName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChName);
      }
      if (EnName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EnName);
      }
      if (ClassName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ClassName);
      }
      if (ChDescrip.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ChDescrip);
      }
      if (EnDescrip.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EnDescrip);
      }
      if (IconPath.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(IconPath);
      }
      if (VFXPrefabPath.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(VFXPrefabPath);
      }
      if (AudioPath.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(AudioPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ID);
      }
      if (ChName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChName);
      }
      if (EnName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EnName);
      }
      if (ClassName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ClassName);
      }
      if (ChDescrip.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ChDescrip);
      }
      if (EnDescrip.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(EnDescrip);
      }
      if (IconPath.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(IconPath);
      }
      if (VFXPrefabPath.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(VFXPrefabPath);
      }
      if (AudioPath.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(AudioPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ID);
      }
      if (ChName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChName);
      }
      if (EnName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EnName);
      }
      if (ClassName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClassName);
      }
      if (ChDescrip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChDescrip);
      }
      if (EnDescrip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EnDescrip);
      }
      if (IconPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconPath);
      }
      if (VFXPrefabPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VFXPrefabPath);
      }
      if (AudioPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AudioPath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SkEftBaseCfg other) {
      if (other == null) {
        return;
      }
      if (other.ID != 0) {
        ID = other.ID;
      }
      if (other.ChName.Length != 0) {
        ChName = other.ChName;
      }
      if (other.EnName.Length != 0) {
        EnName = other.EnName;
      }
      if (other.ClassName.Length != 0) {
        ClassName = other.ClassName;
      }
      if (other.ChDescrip.Length != 0) {
        ChDescrip = other.ChDescrip;
      }
      if (other.EnDescrip.Length != 0) {
        EnDescrip = other.EnDescrip;
      }
      if (other.IconPath.Length != 0) {
        IconPath = other.IconPath;
      }
      if (other.VFXPrefabPath.Length != 0) {
        VFXPrefabPath = other.VFXPrefabPath;
      }
      if (other.AudioPath.Length != 0) {
        AudioPath = other.AudioPath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadUInt32();
            break;
          }
          case 18: {
            ChName = input.ReadString();
            break;
          }
          case 26: {
            EnName = input.ReadString();
            break;
          }
          case 34: {
            ClassName = input.ReadString();
            break;
          }
          case 42: {
            ChDescrip = input.ReadString();
            break;
          }
          case 50: {
            EnDescrip = input.ReadString();
            break;
          }
          case 58: {
            IconPath = input.ReadString();
            break;
          }
          case 66: {
            VFXPrefabPath = input.ReadString();
            break;
          }
          case 74: {
            AudioPath = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ID = input.ReadUInt32();
            break;
          }
          case 18: {
            ChName = input.ReadString();
            break;
          }
          case 26: {
            EnName = input.ReadString();
            break;
          }
          case 34: {
            ClassName = input.ReadString();
            break;
          }
          case 42: {
            ChDescrip = input.ReadString();
            break;
          }
          case 50: {
            EnDescrip = input.ReadString();
            break;
          }
          case 58: {
            IconPath = input.ReadString();
            break;
          }
          case 66: {
            VFXPrefabPath = input.ReadString();
            break;
          }
          case 74: {
            AudioPath = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SkillEffectCfg_Data : pb::IMessage<SkillEffectCfg_Data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SkillEffectCfg_Data> _parser = new pb::MessageParser<SkillEffectCfg_Data>(() => new SkillEffectCfg_Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SkillEffectCfg_Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DongciDaci.SkillEffectCfgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillEffectCfg_Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillEffectCfg_Data(SkillEffectCfg_Data other) : this() {
      skEftBaseCfgItems_ = other.skEftBaseCfgItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillEffectCfg_Data Clone() {
      return new SkillEffectCfg_Data(this);
    }

    /// <summary>Field number for the "SkEftBaseCfg_items" field.</summary>
    public const int SkEftBaseCfgItemsFieldNumber = 1;
    private static readonly pbc::MapField<uint, global::DongciDaci.SkEftBaseCfg>.Codec _map_skEftBaseCfgItems_codec
        = new pbc::MapField<uint, global::DongciDaci.SkEftBaseCfg>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForMessage(18, global::DongciDaci.SkEftBaseCfg.Parser), 10);
    private readonly pbc::MapField<uint, global::DongciDaci.SkEftBaseCfg> skEftBaseCfgItems_ = new pbc::MapField<uint, global::DongciDaci.SkEftBaseCfg>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, global::DongciDaci.SkEftBaseCfg> SkEftBaseCfgItems {
      get { return skEftBaseCfgItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SkillEffectCfg_Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SkillEffectCfg_Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!SkEftBaseCfgItems.Equals(other.SkEftBaseCfgItems)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= SkEftBaseCfgItems.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      skEftBaseCfgItems_.WriteTo(output, _map_skEftBaseCfgItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      skEftBaseCfgItems_.WriteTo(ref output, _map_skEftBaseCfgItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += skEftBaseCfgItems_.CalculateSize(_map_skEftBaseCfgItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SkillEffectCfg_Data other) {
      if (other == null) {
        return;
      }
      skEftBaseCfgItems_.MergeFrom(other.skEftBaseCfgItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            skEftBaseCfgItems_.AddEntriesFrom(input, _map_skEftBaseCfgItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            skEftBaseCfgItems_.AddEntriesFrom(ref input, _map_skEftBaseCfgItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
