# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HeroCfg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rHeroCfg.proto\x12\nDongciDaci\"\x83\x03\n\x0bHeroBaseCfg\x12\n\n\x02ID\x18\x01 \x01(\r\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0e\n\x06Prefab\x18\x03 \x01(\t\x12\r\n\x05Speed\x18\x04 \x01(\x02\x12\x14\n\x0c\x44\x61shDistance\x18\x05 \x01(\x02\x12\x14\n\x0c\x41ttackRadius\x18\x06 \x01(\x02\x12\x16\n\x0eInteractRadius\x18\x07 \x01(\x02\x12\x14\n\x0c\x46ollowRadius\x18\x08 \x01(\x02\x12\x11\n\tTurnSpeed\x18\t \x01(\x02\x12\r\n\x05MaxHp\x18\n \x01(\x05\x12\x12\n\nBaseAttack\x18\x0b \x01(\x05\x12\x13\n\x0b\x44\x65\x66\x65nseRate\x18\x0c \x01(\x02\x12\x14\n\x0c\x43riticalRate\x18\r \x01(\x02\x12\x17\n\x0f\x43riticalDmgRate\x18\x0e \x01(\x02\x12\x11\n\tDodgeRate\x18\x0f \x01(\x02\x12\x11\n\tMoveSpeed\x18\x10 \x01(\x02\x12\x17\n\x0f\x45xtraEnergyGain\x18\x12 \x01(\x05\x12\x15\n\rBeatTolerance\x18\x13 \x01(\x02\x12\x11\n\tLuckyRate\x18\x14 \x01(\x05\"\xab\x01\n\x0cHeroCfg_Data\x12I\n\x11HeroBaseCfg_items\x18\x01 \x03(\x0b\x32..DongciDaci.HeroCfg_Data.HeroBaseCfgItemsEntry\x1aP\n\x15HeroBaseCfgItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.DongciDaci.HeroBaseCfg:\x02\x38\x01\x42#\n!com.trinitigames.server.conf.autob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HeroCfg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.trinitigames.server.conf.auto'
  _HEROCFG_DATA_HEROBASECFGITEMSENTRY._options = None
  _HEROCFG_DATA_HEROBASECFGITEMSENTRY._serialized_options = b'8\001'
  _HEROBASECFG._serialized_start=30
  _HEROBASECFG._serialized_end=417
  _HEROCFG_DATA._serialized_start=420
  _HEROCFG_DATA._serialized_end=591
  _HEROCFG_DATA_HEROBASECFGITEMSENTRY._serialized_start=511
  _HEROCFG_DATA_HEROBASECFGITEMSENTRY._serialized_end=591
# @@protoc_insertion_point(module_scope)
