# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HeroCfg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HeroCfg.proto',
  package='DongciDaci',
  syntax='proto3',
  serialized_options=_b('\n!com.trinitigames.server.conf.auto'),
  serialized_pb=_b('\n\rHeroCfg.proto\x12\nDongciDaci\"\xf0\x02\n\x0bHeroBaseCfg\x12\n\n\x02ID\x18\x01 \x01(\r\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0e\n\x06Prefab\x18\x03 \x01(\t\x12\r\n\x05Speed\x18\x04 \x01(\x02\x12\x14\n\x0c\x44\x61shDistance\x18\x05 \x01(\x02\x12\x14\n\x0c\x41ttackRadius\x18\x06 \x01(\x02\x12\x16\n\x0eInteractRadius\x18\x07 \x01(\x02\x12\x14\n\x0c\x46ollowRadius\x18\x08 \x01(\x02\x12\r\n\x05MaxHp\x18\t \x01(\x05\x12\x12\n\nBaseAttack\x18\n \x01(\x05\x12\x13\n\x0b\x44\x65\x66\x65nseRate\x18\x0b \x01(\x02\x12\x14\n\x0c\x43riticalRate\x18\x0c \x01(\x02\x12\x17\n\x0f\x43riticalDmgRate\x18\r \x01(\x02\x12\x11\n\tDodgeRate\x18\x0e \x01(\x02\x12\x11\n\tMoveSpeed\x18\x0f \x01(\x02\x12\x17\n\x0f\x45xtraEnergyGain\x18\x10 \x01(\x05\x12\x15\n\rBeatTolerance\x18\x11 \x01(\x02\x12\x11\n\tLuckyRate\x18\x12 \x01(\x05\"\xab\x01\n\x0cHeroCfg_Data\x12I\n\x11HeroBaseCfg_items\x18\x01 \x03(\x0b\x32..DongciDaci.HeroCfg_Data.HeroBaseCfgItemsEntry\x1aP\n\x15HeroBaseCfgItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.DongciDaci.HeroBaseCfg:\x02\x38\x01\x42#\n!com.trinitigames.server.conf.autob\x06proto3')
)




_HEROBASECFG = _descriptor.Descriptor(
  name='HeroBaseCfg',
  full_name='DongciDaci.HeroBaseCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='DongciDaci.HeroBaseCfg.ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='DongciDaci.HeroBaseCfg.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Prefab', full_name='DongciDaci.HeroBaseCfg.Prefab', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Speed', full_name='DongciDaci.HeroBaseCfg.Speed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DashDistance', full_name='DongciDaci.HeroBaseCfg.DashDistance', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AttackRadius', full_name='DongciDaci.HeroBaseCfg.AttackRadius', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='InteractRadius', full_name='DongciDaci.HeroBaseCfg.InteractRadius', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FollowRadius', full_name='DongciDaci.HeroBaseCfg.FollowRadius', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaxHp', full_name='DongciDaci.HeroBaseCfg.MaxHp', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BaseAttack', full_name='DongciDaci.HeroBaseCfg.BaseAttack', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DefenseRate', full_name='DongciDaci.HeroBaseCfg.DefenseRate', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CriticalRate', full_name='DongciDaci.HeroBaseCfg.CriticalRate', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CriticalDmgRate', full_name='DongciDaci.HeroBaseCfg.CriticalDmgRate', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DodgeRate', full_name='DongciDaci.HeroBaseCfg.DodgeRate', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MoveSpeed', full_name='DongciDaci.HeroBaseCfg.MoveSpeed', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ExtraEnergyGain', full_name='DongciDaci.HeroBaseCfg.ExtraEnergyGain', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BeatTolerance', full_name='DongciDaci.HeroBaseCfg.BeatTolerance', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LuckyRate', full_name='DongciDaci.HeroBaseCfg.LuckyRate', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=398,
)


_HEROCFG_DATA_HEROBASECFGITEMSENTRY = _descriptor.Descriptor(
  name='HeroBaseCfgItemsEntry',
  full_name='DongciDaci.HeroCfg_Data.HeroBaseCfgItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DongciDaci.HeroCfg_Data.HeroBaseCfgItemsEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DongciDaci.HeroCfg_Data.HeroBaseCfgItemsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=572,
)

_HEROCFG_DATA = _descriptor.Descriptor(
  name='HeroCfg_Data',
  full_name='DongciDaci.HeroCfg_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='HeroBaseCfg_items', full_name='DongciDaci.HeroCfg_Data.HeroBaseCfg_items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HEROCFG_DATA_HEROBASECFGITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=572,
)

_HEROCFG_DATA_HEROBASECFGITEMSENTRY.fields_by_name['value'].message_type = _HEROBASECFG
_HEROCFG_DATA_HEROBASECFGITEMSENTRY.containing_type = _HEROCFG_DATA
_HEROCFG_DATA.fields_by_name['HeroBaseCfg_items'].message_type = _HEROCFG_DATA_HEROBASECFGITEMSENTRY
DESCRIPTOR.message_types_by_name['HeroBaseCfg'] = _HEROBASECFG
DESCRIPTOR.message_types_by_name['HeroCfg_Data'] = _HEROCFG_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeroBaseCfg = _reflection.GeneratedProtocolMessageType('HeroBaseCfg', (_message.Message,), dict(
  DESCRIPTOR = _HEROBASECFG,
  __module__ = 'HeroCfg_pb2'
  # @@protoc_insertion_point(class_scope:DongciDaci.HeroBaseCfg)
  ))
_sym_db.RegisterMessage(HeroBaseCfg)

HeroCfg_Data = _reflection.GeneratedProtocolMessageType('HeroCfg_Data', (_message.Message,), dict(

  HeroBaseCfgItemsEntry = _reflection.GeneratedProtocolMessageType('HeroBaseCfgItemsEntry', (_message.Message,), dict(
    DESCRIPTOR = _HEROCFG_DATA_HEROBASECFGITEMSENTRY,
    __module__ = 'HeroCfg_pb2'
    # @@protoc_insertion_point(class_scope:DongciDaci.HeroCfg_Data.HeroBaseCfgItemsEntry)
    ))
  ,
  DESCRIPTOR = _HEROCFG_DATA,
  __module__ = 'HeroCfg_pb2'
  # @@protoc_insertion_point(class_scope:DongciDaci.HeroCfg_Data)
  ))
_sym_db.RegisterMessage(HeroCfg_Data)
_sym_db.RegisterMessage(HeroCfg_Data.HeroBaseCfgItemsEntry)


DESCRIPTOR._options = None
_HEROCFG_DATA_HEROBASECFGITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
