// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeroCfg.proto

package com.trinitigames.server.conf.auto;

public final class HeroCfg {
  private HeroCfg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeroBaseCfgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DongciDaci.HeroBaseCfg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** ID 
     * </pre>
     *
     * <code>uint32 ID = 1;</code>
     * @return The iD.
     */
    int getID();

    /**
     * <pre>
     ** 名称 
     * </pre>
     *
     * <code>string Name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     ** 名称 
     * </pre>
     *
     * <code>string Name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     ** 预制体路径 
     * </pre>
     *
     * <code>string Prefab = 3;</code>
     * @return The prefab.
     */
    java.lang.String getPrefab();
    /**
     * <pre>
     ** 预制体路径 
     * </pre>
     *
     * <code>string Prefab = 3;</code>
     * @return The bytes for prefab.
     */
    com.google.protobuf.ByteString
        getPrefabBytes();

    /**
     * <pre>
     ** 角色的移动速度 
     * </pre>
     *
     * <code>float Speed = 4;</code>
     * @return The speed.
     */
    float getSpeed();

    /**
     * <pre>
     ** 角色的冲刺距离 
     * </pre>
     *
     * <code>float DashDistance = 5;</code>
     * @return The dashDistance.
     */
    float getDashDistance();

    /**
     * <pre>
     ** 攻击半径 
     * </pre>
     *
     * <code>float AttackRadius = 6;</code>
     * @return The attackRadius.
     */
    float getAttackRadius();

    /**
     * <pre>
     ** 交互半径 
     * </pre>
     *
     * <code>float InteractRadius = 7;</code>
     * @return The interactRadius.
     */
    float getInteractRadius();

    /**
     * <pre>
     ** 跟随半径 
     * </pre>
     *
     * <code>float FollowRadius = 8;</code>
     * @return The followRadius.
     */
    float getFollowRadius();

    /**
     * <pre>
     ** 最大生命 
     * </pre>
     *
     * <code>int32 MaxHp = 9;</code>
     * @return The maxHp.
     */
    int getMaxHp();

    /**
     * <pre>
     ** 基础攻击值 
     * </pre>
     *
     * <code>int32 BaseAttack = 10;</code>
     * @return The baseAttack.
     */
    int getBaseAttack();

    /**
     * <pre>
     ** 伤害减免系数 
     * </pre>
     *
     * <code>float DefenseRate = 11;</code>
     * @return The defenseRate.
     */
    float getDefenseRate();

    /**
     * <pre>
     ** 暴击率 
     * </pre>
     *
     * <code>float CriticalRate = 12;</code>
     * @return The criticalRate.
     */
    float getCriticalRate();

    /**
     * <pre>
     ** 暴击伤害 
     * </pre>
     *
     * <code>float CriticalDmgRate = 13;</code>
     * @return The criticalDmgRate.
     */
    float getCriticalDmgRate();

    /**
     * <pre>
     ** 闪避率 
     * </pre>
     *
     * <code>float DodgeRate = 14;</code>
     * @return The dodgeRate.
     */
    float getDodgeRate();

    /**
     * <pre>
     ** 移动速度 
     * </pre>
     *
     * <code>float MoveSpeed = 15;</code>
     * @return The moveSpeed.
     */
    float getMoveSpeed();

    /**
     * <pre>
     ** 额外能量获取 
     * </pre>
     *
     * <code>int32 ExtraEnergyGain = 16;</code>
     * @return The extraEnergyGain.
     */
    int getExtraEnergyGain();

    /**
     * <pre>
     ** 节拍容差 
     * </pre>
     *
     * <code>float BeatTolerance = 17;</code>
     * @return The beatTolerance.
     */
    float getBeatTolerance();

    /**
     * <pre>
     ** 幸运值 
     * </pre>
     *
     * <code>int32 LuckyRate = 18;</code>
     * @return The luckyRate.
     */
    int getLuckyRate();
  }
  /**
   * Protobuf type {@code DongciDaci.HeroBaseCfg}
   */
  public static final class HeroBaseCfg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DongciDaci.HeroBaseCfg)
      HeroBaseCfgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeroBaseCfg.newBuilder() to construct.
    private HeroBaseCfg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeroBaseCfg() {
      name_ = "";
      prefab_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeroBaseCfg();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroBaseCfg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroBaseCfg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg.class, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int iD_ = 0;
    /**
     * <pre>
     ** ID 
     * </pre>
     *
     * <code>uint32 ID = 1;</code>
     * @return The iD.
     */
    @java.lang.Override
    public int getID() {
      return iD_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     ** 名称 
     * </pre>
     *
     * <code>string Name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 名称 
     * </pre>
     *
     * <code>string Name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREFAB_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object prefab_ = "";
    /**
     * <pre>
     ** 预制体路径 
     * </pre>
     *
     * <code>string Prefab = 3;</code>
     * @return The prefab.
     */
    @java.lang.Override
    public java.lang.String getPrefab() {
      java.lang.Object ref = prefab_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prefab_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 预制体路径 
     * </pre>
     *
     * <code>string Prefab = 3;</code>
     * @return The bytes for prefab.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPrefabBytes() {
      java.lang.Object ref = prefab_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prefab_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPEED_FIELD_NUMBER = 4;
    private float speed_ = 0F;
    /**
     * <pre>
     ** 角色的移动速度 
     * </pre>
     *
     * <code>float Speed = 4;</code>
     * @return The speed.
     */
    @java.lang.Override
    public float getSpeed() {
      return speed_;
    }

    public static final int DASHDISTANCE_FIELD_NUMBER = 5;
    private float dashDistance_ = 0F;
    /**
     * <pre>
     ** 角色的冲刺距离 
     * </pre>
     *
     * <code>float DashDistance = 5;</code>
     * @return The dashDistance.
     */
    @java.lang.Override
    public float getDashDistance() {
      return dashDistance_;
    }

    public static final int ATTACKRADIUS_FIELD_NUMBER = 6;
    private float attackRadius_ = 0F;
    /**
     * <pre>
     ** 攻击半径 
     * </pre>
     *
     * <code>float AttackRadius = 6;</code>
     * @return The attackRadius.
     */
    @java.lang.Override
    public float getAttackRadius() {
      return attackRadius_;
    }

    public static final int INTERACTRADIUS_FIELD_NUMBER = 7;
    private float interactRadius_ = 0F;
    /**
     * <pre>
     ** 交互半径 
     * </pre>
     *
     * <code>float InteractRadius = 7;</code>
     * @return The interactRadius.
     */
    @java.lang.Override
    public float getInteractRadius() {
      return interactRadius_;
    }

    public static final int FOLLOWRADIUS_FIELD_NUMBER = 8;
    private float followRadius_ = 0F;
    /**
     * <pre>
     ** 跟随半径 
     * </pre>
     *
     * <code>float FollowRadius = 8;</code>
     * @return The followRadius.
     */
    @java.lang.Override
    public float getFollowRadius() {
      return followRadius_;
    }

    public static final int MAXHP_FIELD_NUMBER = 9;
    private int maxHp_ = 0;
    /**
     * <pre>
     ** 最大生命 
     * </pre>
     *
     * <code>int32 MaxHp = 9;</code>
     * @return The maxHp.
     */
    @java.lang.Override
    public int getMaxHp() {
      return maxHp_;
    }

    public static final int BASEATTACK_FIELD_NUMBER = 10;
    private int baseAttack_ = 0;
    /**
     * <pre>
     ** 基础攻击值 
     * </pre>
     *
     * <code>int32 BaseAttack = 10;</code>
     * @return The baseAttack.
     */
    @java.lang.Override
    public int getBaseAttack() {
      return baseAttack_;
    }

    public static final int DEFENSERATE_FIELD_NUMBER = 11;
    private float defenseRate_ = 0F;
    /**
     * <pre>
     ** 伤害减免系数 
     * </pre>
     *
     * <code>float DefenseRate = 11;</code>
     * @return The defenseRate.
     */
    @java.lang.Override
    public float getDefenseRate() {
      return defenseRate_;
    }

    public static final int CRITICALRATE_FIELD_NUMBER = 12;
    private float criticalRate_ = 0F;
    /**
     * <pre>
     ** 暴击率 
     * </pre>
     *
     * <code>float CriticalRate = 12;</code>
     * @return The criticalRate.
     */
    @java.lang.Override
    public float getCriticalRate() {
      return criticalRate_;
    }

    public static final int CRITICALDMGRATE_FIELD_NUMBER = 13;
    private float criticalDmgRate_ = 0F;
    /**
     * <pre>
     ** 暴击伤害 
     * </pre>
     *
     * <code>float CriticalDmgRate = 13;</code>
     * @return The criticalDmgRate.
     */
    @java.lang.Override
    public float getCriticalDmgRate() {
      return criticalDmgRate_;
    }

    public static final int DODGERATE_FIELD_NUMBER = 14;
    private float dodgeRate_ = 0F;
    /**
     * <pre>
     ** 闪避率 
     * </pre>
     *
     * <code>float DodgeRate = 14;</code>
     * @return The dodgeRate.
     */
    @java.lang.Override
    public float getDodgeRate() {
      return dodgeRate_;
    }

    public static final int MOVESPEED_FIELD_NUMBER = 15;
    private float moveSpeed_ = 0F;
    /**
     * <pre>
     ** 移动速度 
     * </pre>
     *
     * <code>float MoveSpeed = 15;</code>
     * @return The moveSpeed.
     */
    @java.lang.Override
    public float getMoveSpeed() {
      return moveSpeed_;
    }

    public static final int EXTRAENERGYGAIN_FIELD_NUMBER = 16;
    private int extraEnergyGain_ = 0;
    /**
     * <pre>
     ** 额外能量获取 
     * </pre>
     *
     * <code>int32 ExtraEnergyGain = 16;</code>
     * @return The extraEnergyGain.
     */
    @java.lang.Override
    public int getExtraEnergyGain() {
      return extraEnergyGain_;
    }

    public static final int BEATTOLERANCE_FIELD_NUMBER = 17;
    private float beatTolerance_ = 0F;
    /**
     * <pre>
     ** 节拍容差 
     * </pre>
     *
     * <code>float BeatTolerance = 17;</code>
     * @return The beatTolerance.
     */
    @java.lang.Override
    public float getBeatTolerance() {
      return beatTolerance_;
    }

    public static final int LUCKYRATE_FIELD_NUMBER = 18;
    private int luckyRate_ = 0;
    /**
     * <pre>
     ** 幸运值 
     * </pre>
     *
     * <code>int32 LuckyRate = 18;</code>
     * @return The luckyRate.
     */
    @java.lang.Override
    public int getLuckyRate() {
      return luckyRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0) {
        output.writeUInt32(1, iD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(prefab_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, prefab_);
      }
      if (java.lang.Float.floatToRawIntBits(speed_) != 0) {
        output.writeFloat(4, speed_);
      }
      if (java.lang.Float.floatToRawIntBits(dashDistance_) != 0) {
        output.writeFloat(5, dashDistance_);
      }
      if (java.lang.Float.floatToRawIntBits(attackRadius_) != 0) {
        output.writeFloat(6, attackRadius_);
      }
      if (java.lang.Float.floatToRawIntBits(interactRadius_) != 0) {
        output.writeFloat(7, interactRadius_);
      }
      if (java.lang.Float.floatToRawIntBits(followRadius_) != 0) {
        output.writeFloat(8, followRadius_);
      }
      if (maxHp_ != 0) {
        output.writeInt32(9, maxHp_);
      }
      if (baseAttack_ != 0) {
        output.writeInt32(10, baseAttack_);
      }
      if (java.lang.Float.floatToRawIntBits(defenseRate_) != 0) {
        output.writeFloat(11, defenseRate_);
      }
      if (java.lang.Float.floatToRawIntBits(criticalRate_) != 0) {
        output.writeFloat(12, criticalRate_);
      }
      if (java.lang.Float.floatToRawIntBits(criticalDmgRate_) != 0) {
        output.writeFloat(13, criticalDmgRate_);
      }
      if (java.lang.Float.floatToRawIntBits(dodgeRate_) != 0) {
        output.writeFloat(14, dodgeRate_);
      }
      if (java.lang.Float.floatToRawIntBits(moveSpeed_) != 0) {
        output.writeFloat(15, moveSpeed_);
      }
      if (extraEnergyGain_ != 0) {
        output.writeInt32(16, extraEnergyGain_);
      }
      if (java.lang.Float.floatToRawIntBits(beatTolerance_) != 0) {
        output.writeFloat(17, beatTolerance_);
      }
      if (luckyRate_ != 0) {
        output.writeInt32(18, luckyRate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, iD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(prefab_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, prefab_);
      }
      if (java.lang.Float.floatToRawIntBits(speed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, speed_);
      }
      if (java.lang.Float.floatToRawIntBits(dashDistance_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, dashDistance_);
      }
      if (java.lang.Float.floatToRawIntBits(attackRadius_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, attackRadius_);
      }
      if (java.lang.Float.floatToRawIntBits(interactRadius_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, interactRadius_);
      }
      if (java.lang.Float.floatToRawIntBits(followRadius_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, followRadius_);
      }
      if (maxHp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, maxHp_);
      }
      if (baseAttack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, baseAttack_);
      }
      if (java.lang.Float.floatToRawIntBits(defenseRate_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, defenseRate_);
      }
      if (java.lang.Float.floatToRawIntBits(criticalRate_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, criticalRate_);
      }
      if (java.lang.Float.floatToRawIntBits(criticalDmgRate_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(13, criticalDmgRate_);
      }
      if (java.lang.Float.floatToRawIntBits(dodgeRate_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, dodgeRate_);
      }
      if (java.lang.Float.floatToRawIntBits(moveSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, moveSpeed_);
      }
      if (extraEnergyGain_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, extraEnergyGain_);
      }
      if (java.lang.Float.floatToRawIntBits(beatTolerance_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(17, beatTolerance_);
      }
      if (luckyRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, luckyRate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg)) {
        return super.equals(obj);
      }
      com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg other = (com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg) obj;

      if (getID()
          != other.getID()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPrefab()
          .equals(other.getPrefab())) return false;
      if (java.lang.Float.floatToIntBits(getSpeed())
          != java.lang.Float.floatToIntBits(
              other.getSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getDashDistance())
          != java.lang.Float.floatToIntBits(
              other.getDashDistance())) return false;
      if (java.lang.Float.floatToIntBits(getAttackRadius())
          != java.lang.Float.floatToIntBits(
              other.getAttackRadius())) return false;
      if (java.lang.Float.floatToIntBits(getInteractRadius())
          != java.lang.Float.floatToIntBits(
              other.getInteractRadius())) return false;
      if (java.lang.Float.floatToIntBits(getFollowRadius())
          != java.lang.Float.floatToIntBits(
              other.getFollowRadius())) return false;
      if (getMaxHp()
          != other.getMaxHp()) return false;
      if (getBaseAttack()
          != other.getBaseAttack()) return false;
      if (java.lang.Float.floatToIntBits(getDefenseRate())
          != java.lang.Float.floatToIntBits(
              other.getDefenseRate())) return false;
      if (java.lang.Float.floatToIntBits(getCriticalRate())
          != java.lang.Float.floatToIntBits(
              other.getCriticalRate())) return false;
      if (java.lang.Float.floatToIntBits(getCriticalDmgRate())
          != java.lang.Float.floatToIntBits(
              other.getCriticalDmgRate())) return false;
      if (java.lang.Float.floatToIntBits(getDodgeRate())
          != java.lang.Float.floatToIntBits(
              other.getDodgeRate())) return false;
      if (java.lang.Float.floatToIntBits(getMoveSpeed())
          != java.lang.Float.floatToIntBits(
              other.getMoveSpeed())) return false;
      if (getExtraEnergyGain()
          != other.getExtraEnergyGain()) return false;
      if (java.lang.Float.floatToIntBits(getBeatTolerance())
          != java.lang.Float.floatToIntBits(
              other.getBeatTolerance())) return false;
      if (getLuckyRate()
          != other.getLuckyRate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PREFAB_FIELD_NUMBER;
      hash = (53 * hash) + getPrefab().hashCode();
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSpeed());
      hash = (37 * hash) + DASHDISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDashDistance());
      hash = (37 * hash) + ATTACKRADIUS_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAttackRadius());
      hash = (37 * hash) + INTERACTRADIUS_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getInteractRadius());
      hash = (37 * hash) + FOLLOWRADIUS_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFollowRadius());
      hash = (37 * hash) + MAXHP_FIELD_NUMBER;
      hash = (53 * hash) + getMaxHp();
      hash = (37 * hash) + BASEATTACK_FIELD_NUMBER;
      hash = (53 * hash) + getBaseAttack();
      hash = (37 * hash) + DEFENSERATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDefenseRate());
      hash = (37 * hash) + CRITICALRATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCriticalRate());
      hash = (37 * hash) + CRITICALDMGRATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCriticalDmgRate());
      hash = (37 * hash) + DODGERATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDodgeRate());
      hash = (37 * hash) + MOVESPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMoveSpeed());
      hash = (37 * hash) + EXTRAENERGYGAIN_FIELD_NUMBER;
      hash = (53 * hash) + getExtraEnergyGain();
      hash = (37 * hash) + BEATTOLERANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBeatTolerance());
      hash = (37 * hash) + LUCKYRATE_FIELD_NUMBER;
      hash = (53 * hash) + getLuckyRate();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DongciDaci.HeroBaseCfg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DongciDaci.HeroBaseCfg)
        com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroBaseCfg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroBaseCfg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg.class, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg.Builder.class);
      }

      // Construct using com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        iD_ = 0;
        name_ = "";
        prefab_ = "";
        speed_ = 0F;
        dashDistance_ = 0F;
        attackRadius_ = 0F;
        interactRadius_ = 0F;
        followRadius_ = 0F;
        maxHp_ = 0;
        baseAttack_ = 0;
        defenseRate_ = 0F;
        criticalRate_ = 0F;
        criticalDmgRate_ = 0F;
        dodgeRate_ = 0F;
        moveSpeed_ = 0F;
        extraEnergyGain_ = 0;
        beatTolerance_ = 0F;
        luckyRate_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroBaseCfg_descriptor;
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getDefaultInstanceForType() {
        return com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg.getDefaultInstance();
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg build() {
        com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg buildPartial() {
        com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg result = new com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.iD_ = iD_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.prefab_ = prefab_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.speed_ = speed_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.dashDistance_ = dashDistance_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.attackRadius_ = attackRadius_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.interactRadius_ = interactRadius_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.followRadius_ = followRadius_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.maxHp_ = maxHp_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.baseAttack_ = baseAttack_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.defenseRate_ = defenseRate_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.criticalRate_ = criticalRate_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.criticalDmgRate_ = criticalDmgRate_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.dodgeRate_ = dodgeRate_;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.moveSpeed_ = moveSpeed_;
        }
        if (((from_bitField0_ & 0x00008000) != 0)) {
          result.extraEnergyGain_ = extraEnergyGain_;
        }
        if (((from_bitField0_ & 0x00010000) != 0)) {
          result.beatTolerance_ = beatTolerance_;
        }
        if (((from_bitField0_ & 0x00020000) != 0)) {
          result.luckyRate_ = luckyRate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg) {
          return mergeFrom((com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg other) {
        if (other == com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg.getDefaultInstance()) return this;
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPrefab().isEmpty()) {
          prefab_ = other.prefab_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getSpeed() != 0F) {
          setSpeed(other.getSpeed());
        }
        if (other.getDashDistance() != 0F) {
          setDashDistance(other.getDashDistance());
        }
        if (other.getAttackRadius() != 0F) {
          setAttackRadius(other.getAttackRadius());
        }
        if (other.getInteractRadius() != 0F) {
          setInteractRadius(other.getInteractRadius());
        }
        if (other.getFollowRadius() != 0F) {
          setFollowRadius(other.getFollowRadius());
        }
        if (other.getMaxHp() != 0) {
          setMaxHp(other.getMaxHp());
        }
        if (other.getBaseAttack() != 0) {
          setBaseAttack(other.getBaseAttack());
        }
        if (other.getDefenseRate() != 0F) {
          setDefenseRate(other.getDefenseRate());
        }
        if (other.getCriticalRate() != 0F) {
          setCriticalRate(other.getCriticalRate());
        }
        if (other.getCriticalDmgRate() != 0F) {
          setCriticalDmgRate(other.getCriticalDmgRate());
        }
        if (other.getDodgeRate() != 0F) {
          setDodgeRate(other.getDodgeRate());
        }
        if (other.getMoveSpeed() != 0F) {
          setMoveSpeed(other.getMoveSpeed());
        }
        if (other.getExtraEnergyGain() != 0) {
          setExtraEnergyGain(other.getExtraEnergyGain());
        }
        if (other.getBeatTolerance() != 0F) {
          setBeatTolerance(other.getBeatTolerance());
        }
        if (other.getLuckyRate() != 0) {
          setLuckyRate(other.getLuckyRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                iD_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                prefab_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 37: {
                speed_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 45: {
                dashDistance_ = input.readFloat();
                bitField0_ |= 0x00000010;
                break;
              } // case 45
              case 53: {
                attackRadius_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              case 61: {
                interactRadius_ = input.readFloat();
                bitField0_ |= 0x00000040;
                break;
              } // case 61
              case 69: {
                followRadius_ = input.readFloat();
                bitField0_ |= 0x00000080;
                break;
              } // case 69
              case 72: {
                maxHp_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                baseAttack_ = input.readInt32();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 93: {
                defenseRate_ = input.readFloat();
                bitField0_ |= 0x00000400;
                break;
              } // case 93
              case 101: {
                criticalRate_ = input.readFloat();
                bitField0_ |= 0x00000800;
                break;
              } // case 101
              case 109: {
                criticalDmgRate_ = input.readFloat();
                bitField0_ |= 0x00001000;
                break;
              } // case 109
              case 117: {
                dodgeRate_ = input.readFloat();
                bitField0_ |= 0x00002000;
                break;
              } // case 117
              case 125: {
                moveSpeed_ = input.readFloat();
                bitField0_ |= 0x00004000;
                break;
              } // case 125
              case 128: {
                extraEnergyGain_ = input.readInt32();
                bitField0_ |= 0x00008000;
                break;
              } // case 128
              case 141: {
                beatTolerance_ = input.readFloat();
                bitField0_ |= 0x00010000;
                break;
              } // case 141
              case 144: {
                luckyRate_ = input.readInt32();
                bitField0_ |= 0x00020000;
                break;
              } // case 144
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int iD_ ;
      /**
       * <pre>
       ** ID 
       * </pre>
       *
       * <code>uint32 ID = 1;</code>
       * @return The iD.
       */
      @java.lang.Override
      public int getID() {
        return iD_;
      }
      /**
       * <pre>
       ** ID 
       * </pre>
       *
       * <code>uint32 ID = 1;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(int value) {

        iD_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** ID 
       * </pre>
       *
       * <code>uint32 ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iD_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       ** 名称 
       * </pre>
       *
       * <code>string Name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 名称 
       * </pre>
       *
       * <code>string Name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 名称 
       * </pre>
       *
       * <code>string Name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 名称 
       * </pre>
       *
       * <code>string Name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 名称 
       * </pre>
       *
       * <code>string Name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object prefab_ = "";
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string Prefab = 3;</code>
       * @return The prefab.
       */
      public java.lang.String getPrefab() {
        java.lang.Object ref = prefab_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          prefab_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string Prefab = 3;</code>
       * @return The bytes for prefab.
       */
      public com.google.protobuf.ByteString
          getPrefabBytes() {
        java.lang.Object ref = prefab_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prefab_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string Prefab = 3;</code>
       * @param value The prefab to set.
       * @return This builder for chaining.
       */
      public Builder setPrefab(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        prefab_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string Prefab = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrefab() {
        prefab_ = getDefaultInstance().getPrefab();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 预制体路径 
       * </pre>
       *
       * <code>string Prefab = 3;</code>
       * @param value The bytes for prefab to set.
       * @return This builder for chaining.
       */
      public Builder setPrefabBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        prefab_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <pre>
       ** 角色的移动速度 
       * </pre>
       *
       * <code>float Speed = 4;</code>
       * @return The speed.
       */
      @java.lang.Override
      public float getSpeed() {
        return speed_;
      }
      /**
       * <pre>
       ** 角色的移动速度 
       * </pre>
       *
       * <code>float Speed = 4;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(float value) {

        speed_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 角色的移动速度 
       * </pre>
       *
       * <code>float Speed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        speed_ = 0F;
        onChanged();
        return this;
      }

      private float dashDistance_ ;
      /**
       * <pre>
       ** 角色的冲刺距离 
       * </pre>
       *
       * <code>float DashDistance = 5;</code>
       * @return The dashDistance.
       */
      @java.lang.Override
      public float getDashDistance() {
        return dashDistance_;
      }
      /**
       * <pre>
       ** 角色的冲刺距离 
       * </pre>
       *
       * <code>float DashDistance = 5;</code>
       * @param value The dashDistance to set.
       * @return This builder for chaining.
       */
      public Builder setDashDistance(float value) {

        dashDistance_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 角色的冲刺距离 
       * </pre>
       *
       * <code>float DashDistance = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDashDistance() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dashDistance_ = 0F;
        onChanged();
        return this;
      }

      private float attackRadius_ ;
      /**
       * <pre>
       ** 攻击半径 
       * </pre>
       *
       * <code>float AttackRadius = 6;</code>
       * @return The attackRadius.
       */
      @java.lang.Override
      public float getAttackRadius() {
        return attackRadius_;
      }
      /**
       * <pre>
       ** 攻击半径 
       * </pre>
       *
       * <code>float AttackRadius = 6;</code>
       * @param value The attackRadius to set.
       * @return This builder for chaining.
       */
      public Builder setAttackRadius(float value) {

        attackRadius_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 攻击半径 
       * </pre>
       *
       * <code>float AttackRadius = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttackRadius() {
        bitField0_ = (bitField0_ & ~0x00000020);
        attackRadius_ = 0F;
        onChanged();
        return this;
      }

      private float interactRadius_ ;
      /**
       * <pre>
       ** 交互半径 
       * </pre>
       *
       * <code>float InteractRadius = 7;</code>
       * @return The interactRadius.
       */
      @java.lang.Override
      public float getInteractRadius() {
        return interactRadius_;
      }
      /**
       * <pre>
       ** 交互半径 
       * </pre>
       *
       * <code>float InteractRadius = 7;</code>
       * @param value The interactRadius to set.
       * @return This builder for chaining.
       */
      public Builder setInteractRadius(float value) {

        interactRadius_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 交互半径 
       * </pre>
       *
       * <code>float InteractRadius = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearInteractRadius() {
        bitField0_ = (bitField0_ & ~0x00000040);
        interactRadius_ = 0F;
        onChanged();
        return this;
      }

      private float followRadius_ ;
      /**
       * <pre>
       ** 跟随半径 
       * </pre>
       *
       * <code>float FollowRadius = 8;</code>
       * @return The followRadius.
       */
      @java.lang.Override
      public float getFollowRadius() {
        return followRadius_;
      }
      /**
       * <pre>
       ** 跟随半径 
       * </pre>
       *
       * <code>float FollowRadius = 8;</code>
       * @param value The followRadius to set.
       * @return This builder for chaining.
       */
      public Builder setFollowRadius(float value) {

        followRadius_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 跟随半径 
       * </pre>
       *
       * <code>float FollowRadius = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFollowRadius() {
        bitField0_ = (bitField0_ & ~0x00000080);
        followRadius_ = 0F;
        onChanged();
        return this;
      }

      private int maxHp_ ;
      /**
       * <pre>
       ** 最大生命 
       * </pre>
       *
       * <code>int32 MaxHp = 9;</code>
       * @return The maxHp.
       */
      @java.lang.Override
      public int getMaxHp() {
        return maxHp_;
      }
      /**
       * <pre>
       ** 最大生命 
       * </pre>
       *
       * <code>int32 MaxHp = 9;</code>
       * @param value The maxHp to set.
       * @return This builder for chaining.
       */
      public Builder setMaxHp(int value) {

        maxHp_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 最大生命 
       * </pre>
       *
       * <code>int32 MaxHp = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxHp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        maxHp_ = 0;
        onChanged();
        return this;
      }

      private int baseAttack_ ;
      /**
       * <pre>
       ** 基础攻击值 
       * </pre>
       *
       * <code>int32 BaseAttack = 10;</code>
       * @return The baseAttack.
       */
      @java.lang.Override
      public int getBaseAttack() {
        return baseAttack_;
      }
      /**
       * <pre>
       ** 基础攻击值 
       * </pre>
       *
       * <code>int32 BaseAttack = 10;</code>
       * @param value The baseAttack to set.
       * @return This builder for chaining.
       */
      public Builder setBaseAttack(int value) {

        baseAttack_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 基础攻击值 
       * </pre>
       *
       * <code>int32 BaseAttack = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseAttack() {
        bitField0_ = (bitField0_ & ~0x00000200);
        baseAttack_ = 0;
        onChanged();
        return this;
      }

      private float defenseRate_ ;
      /**
       * <pre>
       ** 伤害减免系数 
       * </pre>
       *
       * <code>float DefenseRate = 11;</code>
       * @return The defenseRate.
       */
      @java.lang.Override
      public float getDefenseRate() {
        return defenseRate_;
      }
      /**
       * <pre>
       ** 伤害减免系数 
       * </pre>
       *
       * <code>float DefenseRate = 11;</code>
       * @param value The defenseRate to set.
       * @return This builder for chaining.
       */
      public Builder setDefenseRate(float value) {

        defenseRate_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 伤害减免系数 
       * </pre>
       *
       * <code>float DefenseRate = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefenseRate() {
        bitField0_ = (bitField0_ & ~0x00000400);
        defenseRate_ = 0F;
        onChanged();
        return this;
      }

      private float criticalRate_ ;
      /**
       * <pre>
       ** 暴击率 
       * </pre>
       *
       * <code>float CriticalRate = 12;</code>
       * @return The criticalRate.
       */
      @java.lang.Override
      public float getCriticalRate() {
        return criticalRate_;
      }
      /**
       * <pre>
       ** 暴击率 
       * </pre>
       *
       * <code>float CriticalRate = 12;</code>
       * @param value The criticalRate to set.
       * @return This builder for chaining.
       */
      public Builder setCriticalRate(float value) {

        criticalRate_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 暴击率 
       * </pre>
       *
       * <code>float CriticalRate = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearCriticalRate() {
        bitField0_ = (bitField0_ & ~0x00000800);
        criticalRate_ = 0F;
        onChanged();
        return this;
      }

      private float criticalDmgRate_ ;
      /**
       * <pre>
       ** 暴击伤害 
       * </pre>
       *
       * <code>float CriticalDmgRate = 13;</code>
       * @return The criticalDmgRate.
       */
      @java.lang.Override
      public float getCriticalDmgRate() {
        return criticalDmgRate_;
      }
      /**
       * <pre>
       ** 暴击伤害 
       * </pre>
       *
       * <code>float CriticalDmgRate = 13;</code>
       * @param value The criticalDmgRate to set.
       * @return This builder for chaining.
       */
      public Builder setCriticalDmgRate(float value) {

        criticalDmgRate_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 暴击伤害 
       * </pre>
       *
       * <code>float CriticalDmgRate = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearCriticalDmgRate() {
        bitField0_ = (bitField0_ & ~0x00001000);
        criticalDmgRate_ = 0F;
        onChanged();
        return this;
      }

      private float dodgeRate_ ;
      /**
       * <pre>
       ** 闪避率 
       * </pre>
       *
       * <code>float DodgeRate = 14;</code>
       * @return The dodgeRate.
       */
      @java.lang.Override
      public float getDodgeRate() {
        return dodgeRate_;
      }
      /**
       * <pre>
       ** 闪避率 
       * </pre>
       *
       * <code>float DodgeRate = 14;</code>
       * @param value The dodgeRate to set.
       * @return This builder for chaining.
       */
      public Builder setDodgeRate(float value) {

        dodgeRate_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 闪避率 
       * </pre>
       *
       * <code>float DodgeRate = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearDodgeRate() {
        bitField0_ = (bitField0_ & ~0x00002000);
        dodgeRate_ = 0F;
        onChanged();
        return this;
      }

      private float moveSpeed_ ;
      /**
       * <pre>
       ** 移动速度 
       * </pre>
       *
       * <code>float MoveSpeed = 15;</code>
       * @return The moveSpeed.
       */
      @java.lang.Override
      public float getMoveSpeed() {
        return moveSpeed_;
      }
      /**
       * <pre>
       ** 移动速度 
       * </pre>
       *
       * <code>float MoveSpeed = 15;</code>
       * @param value The moveSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setMoveSpeed(float value) {

        moveSpeed_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 移动速度 
       * </pre>
       *
       * <code>float MoveSpeed = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoveSpeed() {
        bitField0_ = (bitField0_ & ~0x00004000);
        moveSpeed_ = 0F;
        onChanged();
        return this;
      }

      private int extraEnergyGain_ ;
      /**
       * <pre>
       ** 额外能量获取 
       * </pre>
       *
       * <code>int32 ExtraEnergyGain = 16;</code>
       * @return The extraEnergyGain.
       */
      @java.lang.Override
      public int getExtraEnergyGain() {
        return extraEnergyGain_;
      }
      /**
       * <pre>
       ** 额外能量获取 
       * </pre>
       *
       * <code>int32 ExtraEnergyGain = 16;</code>
       * @param value The extraEnergyGain to set.
       * @return This builder for chaining.
       */
      public Builder setExtraEnergyGain(int value) {

        extraEnergyGain_ = value;
        bitField0_ |= 0x00008000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 额外能量获取 
       * </pre>
       *
       * <code>int32 ExtraEnergyGain = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtraEnergyGain() {
        bitField0_ = (bitField0_ & ~0x00008000);
        extraEnergyGain_ = 0;
        onChanged();
        return this;
      }

      private float beatTolerance_ ;
      /**
       * <pre>
       ** 节拍容差 
       * </pre>
       *
       * <code>float BeatTolerance = 17;</code>
       * @return The beatTolerance.
       */
      @java.lang.Override
      public float getBeatTolerance() {
        return beatTolerance_;
      }
      /**
       * <pre>
       ** 节拍容差 
       * </pre>
       *
       * <code>float BeatTolerance = 17;</code>
       * @param value The beatTolerance to set.
       * @return This builder for chaining.
       */
      public Builder setBeatTolerance(float value) {

        beatTolerance_ = value;
        bitField0_ |= 0x00010000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 节拍容差 
       * </pre>
       *
       * <code>float BeatTolerance = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearBeatTolerance() {
        bitField0_ = (bitField0_ & ~0x00010000);
        beatTolerance_ = 0F;
        onChanged();
        return this;
      }

      private int luckyRate_ ;
      /**
       * <pre>
       ** 幸运值 
       * </pre>
       *
       * <code>int32 LuckyRate = 18;</code>
       * @return The luckyRate.
       */
      @java.lang.Override
      public int getLuckyRate() {
        return luckyRate_;
      }
      /**
       * <pre>
       ** 幸运值 
       * </pre>
       *
       * <code>int32 LuckyRate = 18;</code>
       * @param value The luckyRate to set.
       * @return This builder for chaining.
       */
      public Builder setLuckyRate(int value) {

        luckyRate_ = value;
        bitField0_ |= 0x00020000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 幸运值 
       * </pre>
       *
       * <code>int32 LuckyRate = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearLuckyRate() {
        bitField0_ = (bitField0_ & ~0x00020000);
        luckyRate_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DongciDaci.HeroBaseCfg)
    }

    // @@protoc_insertion_point(class_scope:DongciDaci.HeroBaseCfg)
    private static final com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg();
    }

    public static com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeroBaseCfg>
        PARSER = new com.google.protobuf.AbstractParser<HeroBaseCfg>() {
      @java.lang.Override
      public HeroBaseCfg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HeroBaseCfg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeroBaseCfg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeroCfg_DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DongciDaci.HeroCfg_Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    int getHeroBaseCfgItemsCount();
    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    boolean containsHeroBaseCfgItems(
        int key);
    /**
     * Use {@link #getHeroBaseCfgItemsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>
    getHeroBaseCfgItems();
    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>
    getHeroBaseCfgItemsMap();
    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    /* nullable */
com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getHeroBaseCfgItemsOrDefault(
        int key,
        /* nullable */
com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg defaultValue);
    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getHeroBaseCfgItemsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code DongciDaci.HeroCfg_Data}
   */
  public static final class HeroCfg_Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DongciDaci.HeroCfg_Data)
      HeroCfg_DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeroCfg_Data.newBuilder() to construct.
    private HeroCfg_Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeroCfg_Data() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeroCfg_Data();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroCfg_Data_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetHeroBaseCfgItems();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroCfg_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data.class, com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data.Builder.class);
    }

    public static final int HEROBASECFG_ITEMS_FIELD_NUMBER = 1;
    private static final class HeroBaseCfgItemsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>newDefaultInstance(
                  com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroCfg_Data_HeroBaseCfgItemsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> heroBaseCfgItems_;
    private com.google.protobuf.MapField<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>
    internalGetHeroBaseCfgItems() {
      if (heroBaseCfgItems_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeroBaseCfgItemsDefaultEntryHolder.defaultEntry);
      }
      return heroBaseCfgItems_;
    }
    public int getHeroBaseCfgItemsCount() {
      return internalGetHeroBaseCfgItems().getMap().size();
    }
    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    @java.lang.Override
    public boolean containsHeroBaseCfgItems(
        int key) {

      return internalGetHeroBaseCfgItems().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeroBaseCfgItemsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> getHeroBaseCfgItems() {
      return getHeroBaseCfgItemsMap();
    }
    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> getHeroBaseCfgItemsMap() {
      return internalGetHeroBaseCfgItems().getMap();
    }
    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getHeroBaseCfgItemsOrDefault(
        int key,
        /* nullable */
com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg defaultValue) {

      java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> map =
          internalGetHeroBaseCfgItems().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
     */
    @java.lang.Override
    public com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getHeroBaseCfgItemsOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> map =
          internalGetHeroBaseCfgItems().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetHeroBaseCfgItems(),
          HeroBaseCfgItemsDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> entry
           : internalGetHeroBaseCfgItems().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>
        heroBaseCfgItems__ = HeroBaseCfgItemsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, heroBaseCfgItems__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data)) {
        return super.equals(obj);
      }
      com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data other = (com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data) obj;

      if (!internalGetHeroBaseCfgItems().equals(
          other.internalGetHeroBaseCfgItems())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetHeroBaseCfgItems().getMap().isEmpty()) {
        hash = (37 * hash) + HEROBASECFG_ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetHeroBaseCfgItems().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DongciDaci.HeroCfg_Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DongciDaci.HeroCfg_Data)
        com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroCfg_Data_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetHeroBaseCfgItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableHeroBaseCfgItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroCfg_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data.class, com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data.Builder.class);
      }

      // Construct using com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableHeroBaseCfgItems().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trinitigames.server.conf.auto.HeroCfg.internal_static_DongciDaci_HeroCfg_Data_descriptor;
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data getDefaultInstanceForType() {
        return com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data.getDefaultInstance();
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data build() {
        com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data buildPartial() {
        com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data result = new com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.heroBaseCfgItems_ = internalGetHeroBaseCfgItems();
          result.heroBaseCfgItems_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data) {
          return mergeFrom((com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data other) {
        if (other == com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data.getDefaultInstance()) return this;
        internalGetMutableHeroBaseCfgItems().mergeFrom(
            other.internalGetHeroBaseCfgItems());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>
                heroBaseCfgItems__ = input.readMessage(
                    HeroBaseCfgItemsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableHeroBaseCfgItems().getMutableMap().put(
                    heroBaseCfgItems__.getKey(), heroBaseCfgItems__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> heroBaseCfgItems_;
      private com.google.protobuf.MapField<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>
          internalGetHeroBaseCfgItems() {
        if (heroBaseCfgItems_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              HeroBaseCfgItemsDefaultEntryHolder.defaultEntry);
        }
        return heroBaseCfgItems_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>
          internalGetMutableHeroBaseCfgItems() {
        if (heroBaseCfgItems_ == null) {
          heroBaseCfgItems_ = com.google.protobuf.MapField.newMapField(
              HeroBaseCfgItemsDefaultEntryHolder.defaultEntry);
        }
        if (!heroBaseCfgItems_.isMutable()) {
          heroBaseCfgItems_ = heroBaseCfgItems_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return heroBaseCfgItems_;
      }
      public int getHeroBaseCfgItemsCount() {
        return internalGetHeroBaseCfgItems().getMap().size();
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
       */
      @java.lang.Override
      public boolean containsHeroBaseCfgItems(
          int key) {

        return internalGetHeroBaseCfgItems().getMap().containsKey(key);
      }
      /**
       * Use {@link #getHeroBaseCfgItemsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> getHeroBaseCfgItems() {
        return getHeroBaseCfgItemsMap();
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> getHeroBaseCfgItemsMap() {
        return internalGetHeroBaseCfgItems().getMap();
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getHeroBaseCfgItemsOrDefault(
          int key,
          /* nullable */
com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg defaultValue) {

        java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> map =
            internalGetHeroBaseCfgItems().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
       */
      @java.lang.Override
      public com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg getHeroBaseCfgItemsOrThrow(
          int key) {

        java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> map =
            internalGetHeroBaseCfgItems().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearHeroBaseCfgItems() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableHeroBaseCfgItems().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
       */
      public Builder removeHeroBaseCfgItems(
          int key) {

        internalGetMutableHeroBaseCfgItems().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg>
          getMutableHeroBaseCfgItems() {
        bitField0_ |= 0x00000001;
        return internalGetMutableHeroBaseCfgItems().getMutableMap();
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
       */
      public Builder putHeroBaseCfgItems(
          int key,
          com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg value) {

        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableHeroBaseCfgItems().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.HeroBaseCfg&gt; HeroBaseCfg_items = 1;</code>
       */
      public Builder putAllHeroBaseCfgItems(
          java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.HeroCfg.HeroBaseCfg> values) {
        internalGetMutableHeroBaseCfgItems().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DongciDaci.HeroCfg_Data)
    }

    // @@protoc_insertion_point(class_scope:DongciDaci.HeroCfg_Data)
    private static final com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data();
    }

    public static com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeroCfg_Data>
        PARSER = new com.google.protobuf.AbstractParser<HeroCfg_Data>() {
      @java.lang.Override
      public HeroCfg_Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HeroCfg_Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeroCfg_Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.trinitigames.server.conf.auto.HeroCfg.HeroCfg_Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DongciDaci_HeroBaseCfg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DongciDaci_HeroBaseCfg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DongciDaci_HeroCfg_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DongciDaci_HeroCfg_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DongciDaci_HeroCfg_Data_HeroBaseCfgItemsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DongciDaci_HeroCfg_Data_HeroBaseCfgItemsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rHeroCfg.proto\022\nDongciDaci\"\360\002\n\013HeroBase" +
      "Cfg\022\n\n\002ID\030\001 \001(\r\022\014\n\004Name\030\002 \001(\t\022\016\n\006Prefab\030" +
      "\003 \001(\t\022\r\n\005Speed\030\004 \001(\002\022\024\n\014DashDistance\030\005 \001" +
      "(\002\022\024\n\014AttackRadius\030\006 \001(\002\022\026\n\016InteractRadi" +
      "us\030\007 \001(\002\022\024\n\014FollowRadius\030\010 \001(\002\022\r\n\005MaxHp\030" +
      "\t \001(\005\022\022\n\nBaseAttack\030\n \001(\005\022\023\n\013DefenseRate" +
      "\030\013 \001(\002\022\024\n\014CriticalRate\030\014 \001(\002\022\027\n\017Critical" +
      "DmgRate\030\r \001(\002\022\021\n\tDodgeRate\030\016 \001(\002\022\021\n\tMove" +
      "Speed\030\017 \001(\002\022\027\n\017ExtraEnergyGain\030\020 \001(\005\022\025\n\r" +
      "BeatTolerance\030\021 \001(\002\022\021\n\tLuckyRate\030\022 \001(\005\"\253" +
      "\001\n\014HeroCfg_Data\022I\n\021HeroBaseCfg_items\030\001 \003" +
      "(\0132..DongciDaci.HeroCfg_Data.HeroBaseCfg" +
      "ItemsEntry\032P\n\025HeroBaseCfgItemsEntry\022\013\n\003k" +
      "ey\030\001 \001(\r\022&\n\005value\030\002 \001(\0132\027.DongciDaci.Her" +
      "oBaseCfg:\0028\001B#\n!com.trinitigames.server." +
      "conf.autob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DongciDaci_HeroBaseCfg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DongciDaci_HeroBaseCfg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DongciDaci_HeroBaseCfg_descriptor,
        new java.lang.String[] { "ID", "Name", "Prefab", "Speed", "DashDistance", "AttackRadius", "InteractRadius", "FollowRadius", "MaxHp", "BaseAttack", "DefenseRate", "CriticalRate", "CriticalDmgRate", "DodgeRate", "MoveSpeed", "ExtraEnergyGain", "BeatTolerance", "LuckyRate", });
    internal_static_DongciDaci_HeroCfg_Data_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DongciDaci_HeroCfg_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DongciDaci_HeroCfg_Data_descriptor,
        new java.lang.String[] { "HeroBaseCfgItems", });
    internal_static_DongciDaci_HeroCfg_Data_HeroBaseCfgItemsEntry_descriptor =
      internal_static_DongciDaci_HeroCfg_Data_descriptor.getNestedTypes().get(0);
    internal_static_DongciDaci_HeroCfg_Data_HeroBaseCfgItemsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DongciDaci_HeroCfg_Data_HeroBaseCfgItemsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
