// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SkillEffectCfg.proto

package com.trinitigames.server.conf.auto;

public final class SkillEffectCfg {
  private SkillEffectCfg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SkEftBaseCfgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DongciDaci.SkEftBaseCfg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** ID 
     * </pre>
     *
     * <code>uint32 ID = 1;</code>
     * @return The iD.
     */
    int getID();

    /**
     * <pre>
     ** 中文名称 
     * </pre>
     *
     * <code>string ChName = 2;</code>
     * @return The chName.
     */
    java.lang.String getChName();
    /**
     * <pre>
     ** 中文名称 
     * </pre>
     *
     * <code>string ChName = 2;</code>
     * @return The bytes for chName.
     */
    com.google.protobuf.ByteString
        getChNameBytes();

    /**
     * <pre>
     ** 英文名称 
     * </pre>
     *
     * <code>string EnName = 3;</code>
     * @return The enName.
     */
    java.lang.String getEnName();
    /**
     * <pre>
     ** 英文名称 
     * </pre>
     *
     * <code>string EnName = 3;</code>
     * @return The bytes for enName.
     */
    com.google.protobuf.ByteString
        getEnNameBytes();

    /**
     * <pre>
     ** 类名 
     * </pre>
     *
     * <code>string ClassName = 4;</code>
     * @return The className.
     */
    java.lang.String getClassName();
    /**
     * <pre>
     ** 类名 
     * </pre>
     *
     * <code>string ClassName = 4;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <pre>
     ** 中文描述 
     * </pre>
     *
     * <code>string ChDescrip = 5;</code>
     * @return The chDescrip.
     */
    java.lang.String getChDescrip();
    /**
     * <pre>
     ** 中文描述 
     * </pre>
     *
     * <code>string ChDescrip = 5;</code>
     * @return The bytes for chDescrip.
     */
    com.google.protobuf.ByteString
        getChDescripBytes();

    /**
     * <pre>
     ** 英文描述 
     * </pre>
     *
     * <code>string EnDescrip = 6;</code>
     * @return The enDescrip.
     */
    java.lang.String getEnDescrip();
    /**
     * <pre>
     ** 英文描述 
     * </pre>
     *
     * <code>string EnDescrip = 6;</code>
     * @return The bytes for enDescrip.
     */
    com.google.protobuf.ByteString
        getEnDescripBytes();

    /**
     * <pre>
     ** 图标路径 
     * </pre>
     *
     * <code>string IconPath = 7;</code>
     * @return The iconPath.
     */
    java.lang.String getIconPath();
    /**
     * <pre>
     ** 图标路径 
     * </pre>
     *
     * <code>string IconPath = 7;</code>
     * @return The bytes for iconPath.
     */
    com.google.protobuf.ByteString
        getIconPathBytes();

    /**
     * <pre>
     ** 特效路径 
     * </pre>
     *
     * <code>string VFXPrefabPath = 8;</code>
     * @return The vFXPrefabPath.
     */
    java.lang.String getVFXPrefabPath();
    /**
     * <pre>
     ** 特效路径 
     * </pre>
     *
     * <code>string VFXPrefabPath = 8;</code>
     * @return The bytes for vFXPrefabPath.
     */
    com.google.protobuf.ByteString
        getVFXPrefabPathBytes();

    /**
     * <pre>
     ** 音频路径 
     * </pre>
     *
     * <code>string AudioPath = 9;</code>
     * @return The audioPath.
     */
    java.lang.String getAudioPath();
    /**
     * <pre>
     ** 音频路径 
     * </pre>
     *
     * <code>string AudioPath = 9;</code>
     * @return The bytes for audioPath.
     */
    com.google.protobuf.ByteString
        getAudioPathBytes();
  }
  /**
   * Protobuf type {@code DongciDaci.SkEftBaseCfg}
   */
  public static final class SkEftBaseCfg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DongciDaci.SkEftBaseCfg)
      SkEftBaseCfgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SkEftBaseCfg.newBuilder() to construct.
    private SkEftBaseCfg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SkEftBaseCfg() {
      chName_ = "";
      enName_ = "";
      className_ = "";
      chDescrip_ = "";
      enDescrip_ = "";
      iconPath_ = "";
      vFXPrefabPath_ = "";
      audioPath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SkEftBaseCfg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SkEftBaseCfg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              iD_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              chName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              enName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              className_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              chDescrip_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              enDescrip_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              iconPath_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              vFXPrefabPath_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              audioPath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkEftBaseCfg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkEftBaseCfg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg.class, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int iD_;
    /**
     * <pre>
     ** ID 
     * </pre>
     *
     * <code>uint32 ID = 1;</code>
     * @return The iD.
     */
    @java.lang.Override
    public int getID() {
      return iD_;
    }

    public static final int CHNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object chName_;
    /**
     * <pre>
     ** 中文名称 
     * </pre>
     *
     * <code>string ChName = 2;</code>
     * @return The chName.
     */
    @java.lang.Override
    public java.lang.String getChName() {
      java.lang.Object ref = chName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 中文名称 
     * </pre>
     *
     * <code>string ChName = 2;</code>
     * @return The bytes for chName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChNameBytes() {
      java.lang.Object ref = chName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object enName_;
    /**
     * <pre>
     ** 英文名称 
     * </pre>
     *
     * <code>string EnName = 3;</code>
     * @return The enName.
     */
    @java.lang.Override
    public java.lang.String getEnName() {
      java.lang.Object ref = enName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        enName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 英文名称 
     * </pre>
     *
     * <code>string EnName = 3;</code>
     * @return The bytes for enName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEnNameBytes() {
      java.lang.Object ref = enName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object className_;
    /**
     * <pre>
     ** 类名 
     * </pre>
     *
     * <code>string ClassName = 4;</code>
     * @return The className.
     */
    @java.lang.Override
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 类名 
     * </pre>
     *
     * <code>string ClassName = 4;</code>
     * @return The bytes for className.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHDESCRIP_FIELD_NUMBER = 5;
    private volatile java.lang.Object chDescrip_;
    /**
     * <pre>
     ** 中文描述 
     * </pre>
     *
     * <code>string ChDescrip = 5;</code>
     * @return The chDescrip.
     */
    @java.lang.Override
    public java.lang.String getChDescrip() {
      java.lang.Object ref = chDescrip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chDescrip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 中文描述 
     * </pre>
     *
     * <code>string ChDescrip = 5;</code>
     * @return The bytes for chDescrip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChDescripBytes() {
      java.lang.Object ref = chDescrip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chDescrip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDESCRIP_FIELD_NUMBER = 6;
    private volatile java.lang.Object enDescrip_;
    /**
     * <pre>
     ** 英文描述 
     * </pre>
     *
     * <code>string EnDescrip = 6;</code>
     * @return The enDescrip.
     */
    @java.lang.Override
    public java.lang.String getEnDescrip() {
      java.lang.Object ref = enDescrip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        enDescrip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 英文描述 
     * </pre>
     *
     * <code>string EnDescrip = 6;</code>
     * @return The bytes for enDescrip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEnDescripBytes() {
      java.lang.Object ref = enDescrip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enDescrip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICONPATH_FIELD_NUMBER = 7;
    private volatile java.lang.Object iconPath_;
    /**
     * <pre>
     ** 图标路径 
     * </pre>
     *
     * <code>string IconPath = 7;</code>
     * @return The iconPath.
     */
    @java.lang.Override
    public java.lang.String getIconPath() {
      java.lang.Object ref = iconPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iconPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 图标路径 
     * </pre>
     *
     * <code>string IconPath = 7;</code>
     * @return The bytes for iconPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIconPathBytes() {
      java.lang.Object ref = iconPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VFXPREFABPATH_FIELD_NUMBER = 8;
    private volatile java.lang.Object vFXPrefabPath_;
    /**
     * <pre>
     ** 特效路径 
     * </pre>
     *
     * <code>string VFXPrefabPath = 8;</code>
     * @return The vFXPrefabPath.
     */
    @java.lang.Override
    public java.lang.String getVFXPrefabPath() {
      java.lang.Object ref = vFXPrefabPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vFXPrefabPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 特效路径 
     * </pre>
     *
     * <code>string VFXPrefabPath = 8;</code>
     * @return The bytes for vFXPrefabPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVFXPrefabPathBytes() {
      java.lang.Object ref = vFXPrefabPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vFXPrefabPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUDIOPATH_FIELD_NUMBER = 9;
    private volatile java.lang.Object audioPath_;
    /**
     * <pre>
     ** 音频路径 
     * </pre>
     *
     * <code>string AudioPath = 9;</code>
     * @return The audioPath.
     */
    @java.lang.Override
    public java.lang.String getAudioPath() {
      java.lang.Object ref = audioPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        audioPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 音频路径 
     * </pre>
     *
     * <code>string AudioPath = 9;</code>
     * @return The bytes for audioPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAudioPathBytes() {
      java.lang.Object ref = audioPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        audioPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0) {
        output.writeUInt32(1, iD_);
      }
      if (!getChNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chName_);
      }
      if (!getEnNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, enName_);
      }
      if (!getClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, className_);
      }
      if (!getChDescripBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, chDescrip_);
      }
      if (!getEnDescripBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, enDescrip_);
      }
      if (!getIconPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, iconPath_);
      }
      if (!getVFXPrefabPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, vFXPrefabPath_);
      }
      if (!getAudioPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, audioPath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, iD_);
      }
      if (!getChNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chName_);
      }
      if (!getEnNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, enName_);
      }
      if (!getClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, className_);
      }
      if (!getChDescripBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, chDescrip_);
      }
      if (!getEnDescripBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, enDescrip_);
      }
      if (!getIconPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, iconPath_);
      }
      if (!getVFXPrefabPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, vFXPrefabPath_);
      }
      if (!getAudioPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, audioPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg)) {
        return super.equals(obj);
      }
      com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg other = (com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg) obj;

      if (getID()
          != other.getID()) return false;
      if (!getChName()
          .equals(other.getChName())) return false;
      if (!getEnName()
          .equals(other.getEnName())) return false;
      if (!getClassName()
          .equals(other.getClassName())) return false;
      if (!getChDescrip()
          .equals(other.getChDescrip())) return false;
      if (!getEnDescrip()
          .equals(other.getEnDescrip())) return false;
      if (!getIconPath()
          .equals(other.getIconPath())) return false;
      if (!getVFXPrefabPath()
          .equals(other.getVFXPrefabPath())) return false;
      if (!getAudioPath()
          .equals(other.getAudioPath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + CHNAME_FIELD_NUMBER;
      hash = (53 * hash) + getChName().hashCode();
      hash = (37 * hash) + ENNAME_FIELD_NUMBER;
      hash = (53 * hash) + getEnName().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + CHDESCRIP_FIELD_NUMBER;
      hash = (53 * hash) + getChDescrip().hashCode();
      hash = (37 * hash) + ENDESCRIP_FIELD_NUMBER;
      hash = (53 * hash) + getEnDescrip().hashCode();
      hash = (37 * hash) + ICONPATH_FIELD_NUMBER;
      hash = (53 * hash) + getIconPath().hashCode();
      hash = (37 * hash) + VFXPREFABPATH_FIELD_NUMBER;
      hash = (53 * hash) + getVFXPrefabPath().hashCode();
      hash = (37 * hash) + AUDIOPATH_FIELD_NUMBER;
      hash = (53 * hash) + getAudioPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DongciDaci.SkEftBaseCfg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DongciDaci.SkEftBaseCfg)
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkEftBaseCfg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkEftBaseCfg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg.class, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg.Builder.class);
      }

      // Construct using com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        iD_ = 0;

        chName_ = "";

        enName_ = "";

        className_ = "";

        chDescrip_ = "";

        enDescrip_ = "";

        iconPath_ = "";

        vFXPrefabPath_ = "";

        audioPath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkEftBaseCfg_descriptor;
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getDefaultInstanceForType() {
        return com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg.getDefaultInstance();
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg build() {
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg buildPartial() {
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg result = new com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg(this);
        result.iD_ = iD_;
        result.chName_ = chName_;
        result.enName_ = enName_;
        result.className_ = className_;
        result.chDescrip_ = chDescrip_;
        result.enDescrip_ = enDescrip_;
        result.iconPath_ = iconPath_;
        result.vFXPrefabPath_ = vFXPrefabPath_;
        result.audioPath_ = audioPath_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg) {
          return mergeFrom((com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg other) {
        if (other == com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg.getDefaultInstance()) return this;
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getChName().isEmpty()) {
          chName_ = other.chName_;
          onChanged();
        }
        if (!other.getEnName().isEmpty()) {
          enName_ = other.enName_;
          onChanged();
        }
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          onChanged();
        }
        if (!other.getChDescrip().isEmpty()) {
          chDescrip_ = other.chDescrip_;
          onChanged();
        }
        if (!other.getEnDescrip().isEmpty()) {
          enDescrip_ = other.enDescrip_;
          onChanged();
        }
        if (!other.getIconPath().isEmpty()) {
          iconPath_ = other.iconPath_;
          onChanged();
        }
        if (!other.getVFXPrefabPath().isEmpty()) {
          vFXPrefabPath_ = other.vFXPrefabPath_;
          onChanged();
        }
        if (!other.getAudioPath().isEmpty()) {
          audioPath_ = other.audioPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iD_ ;
      /**
       * <pre>
       ** ID 
       * </pre>
       *
       * <code>uint32 ID = 1;</code>
       * @return The iD.
       */
      @java.lang.Override
      public int getID() {
        return iD_;
      }
      /**
       * <pre>
       ** ID 
       * </pre>
       *
       * <code>uint32 ID = 1;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(int value) {
        
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** ID 
       * </pre>
       *
       * <code>uint32 ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        
        iD_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object chName_ = "";
      /**
       * <pre>
       ** 中文名称 
       * </pre>
       *
       * <code>string ChName = 2;</code>
       * @return The chName.
       */
      public java.lang.String getChName() {
        java.lang.Object ref = chName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 中文名称 
       * </pre>
       *
       * <code>string ChName = 2;</code>
       * @return The bytes for chName.
       */
      public com.google.protobuf.ByteString
          getChNameBytes() {
        java.lang.Object ref = chName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 中文名称 
       * </pre>
       *
       * <code>string ChName = 2;</code>
       * @param value The chName to set.
       * @return This builder for chaining.
       */
      public Builder setChName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 中文名称 
       * </pre>
       *
       * <code>string ChName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChName() {
        
        chName_ = getDefaultInstance().getChName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 中文名称 
       * </pre>
       *
       * <code>string ChName = 2;</code>
       * @param value The bytes for chName to set.
       * @return This builder for chaining.
       */
      public Builder setChNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object enName_ = "";
      /**
       * <pre>
       ** 英文名称 
       * </pre>
       *
       * <code>string EnName = 3;</code>
       * @return The enName.
       */
      public java.lang.String getEnName() {
        java.lang.Object ref = enName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          enName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 英文名称 
       * </pre>
       *
       * <code>string EnName = 3;</code>
       * @return The bytes for enName.
       */
      public com.google.protobuf.ByteString
          getEnNameBytes() {
        java.lang.Object ref = enName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          enName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 英文名称 
       * </pre>
       *
       * <code>string EnName = 3;</code>
       * @param value The enName to set.
       * @return This builder for chaining.
       */
      public Builder setEnName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        enName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 英文名称 
       * </pre>
       *
       * <code>string EnName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnName() {
        
        enName_ = getDefaultInstance().getEnName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 英文名称 
       * </pre>
       *
       * <code>string EnName = 3;</code>
       * @param value The bytes for enName to set.
       * @return This builder for chaining.
       */
      public Builder setEnNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        enName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object className_ = "";
      /**
       * <pre>
       ** 类名 
       * </pre>
       *
       * <code>string ClassName = 4;</code>
       * @return The className.
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 类名 
       * </pre>
       *
       * <code>string ClassName = 4;</code>
       * @return The bytes for className.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 类名 
       * </pre>
       *
       * <code>string ClassName = 4;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 类名 
       * </pre>
       *
       * <code>string ClassName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 类名 
       * </pre>
       *
       * <code>string ClassName = 4;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        className_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object chDescrip_ = "";
      /**
       * <pre>
       ** 中文描述 
       * </pre>
       *
       * <code>string ChDescrip = 5;</code>
       * @return The chDescrip.
       */
      public java.lang.String getChDescrip() {
        java.lang.Object ref = chDescrip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chDescrip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 中文描述 
       * </pre>
       *
       * <code>string ChDescrip = 5;</code>
       * @return The bytes for chDescrip.
       */
      public com.google.protobuf.ByteString
          getChDescripBytes() {
        java.lang.Object ref = chDescrip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chDescrip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 中文描述 
       * </pre>
       *
       * <code>string ChDescrip = 5;</code>
       * @param value The chDescrip to set.
       * @return This builder for chaining.
       */
      public Builder setChDescrip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chDescrip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 中文描述 
       * </pre>
       *
       * <code>string ChDescrip = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChDescrip() {
        
        chDescrip_ = getDefaultInstance().getChDescrip();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 中文描述 
       * </pre>
       *
       * <code>string ChDescrip = 5;</code>
       * @param value The bytes for chDescrip to set.
       * @return This builder for chaining.
       */
      public Builder setChDescripBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chDescrip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object enDescrip_ = "";
      /**
       * <pre>
       ** 英文描述 
       * </pre>
       *
       * <code>string EnDescrip = 6;</code>
       * @return The enDescrip.
       */
      public java.lang.String getEnDescrip() {
        java.lang.Object ref = enDescrip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          enDescrip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 英文描述 
       * </pre>
       *
       * <code>string EnDescrip = 6;</code>
       * @return The bytes for enDescrip.
       */
      public com.google.protobuf.ByteString
          getEnDescripBytes() {
        java.lang.Object ref = enDescrip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          enDescrip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 英文描述 
       * </pre>
       *
       * <code>string EnDescrip = 6;</code>
       * @param value The enDescrip to set.
       * @return This builder for chaining.
       */
      public Builder setEnDescrip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        enDescrip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 英文描述 
       * </pre>
       *
       * <code>string EnDescrip = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnDescrip() {
        
        enDescrip_ = getDefaultInstance().getEnDescrip();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 英文描述 
       * </pre>
       *
       * <code>string EnDescrip = 6;</code>
       * @param value The bytes for enDescrip to set.
       * @return This builder for chaining.
       */
      public Builder setEnDescripBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        enDescrip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iconPath_ = "";
      /**
       * <pre>
       ** 图标路径 
       * </pre>
       *
       * <code>string IconPath = 7;</code>
       * @return The iconPath.
       */
      public java.lang.String getIconPath() {
        java.lang.Object ref = iconPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iconPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 图标路径 
       * </pre>
       *
       * <code>string IconPath = 7;</code>
       * @return The bytes for iconPath.
       */
      public com.google.protobuf.ByteString
          getIconPathBytes() {
        java.lang.Object ref = iconPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iconPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 图标路径 
       * </pre>
       *
       * <code>string IconPath = 7;</code>
       * @param value The iconPath to set.
       * @return This builder for chaining.
       */
      public Builder setIconPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iconPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 图标路径 
       * </pre>
       *
       * <code>string IconPath = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIconPath() {
        
        iconPath_ = getDefaultInstance().getIconPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 图标路径 
       * </pre>
       *
       * <code>string IconPath = 7;</code>
       * @param value The bytes for iconPath to set.
       * @return This builder for chaining.
       */
      public Builder setIconPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iconPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object vFXPrefabPath_ = "";
      /**
       * <pre>
       ** 特效路径 
       * </pre>
       *
       * <code>string VFXPrefabPath = 8;</code>
       * @return The vFXPrefabPath.
       */
      public java.lang.String getVFXPrefabPath() {
        java.lang.Object ref = vFXPrefabPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vFXPrefabPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 特效路径 
       * </pre>
       *
       * <code>string VFXPrefabPath = 8;</code>
       * @return The bytes for vFXPrefabPath.
       */
      public com.google.protobuf.ByteString
          getVFXPrefabPathBytes() {
        java.lang.Object ref = vFXPrefabPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vFXPrefabPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 特效路径 
       * </pre>
       *
       * <code>string VFXPrefabPath = 8;</code>
       * @param value The vFXPrefabPath to set.
       * @return This builder for chaining.
       */
      public Builder setVFXPrefabPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vFXPrefabPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 特效路径 
       * </pre>
       *
       * <code>string VFXPrefabPath = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearVFXPrefabPath() {
        
        vFXPrefabPath_ = getDefaultInstance().getVFXPrefabPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 特效路径 
       * </pre>
       *
       * <code>string VFXPrefabPath = 8;</code>
       * @param value The bytes for vFXPrefabPath to set.
       * @return This builder for chaining.
       */
      public Builder setVFXPrefabPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vFXPrefabPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object audioPath_ = "";
      /**
       * <pre>
       ** 音频路径 
       * </pre>
       *
       * <code>string AudioPath = 9;</code>
       * @return The audioPath.
       */
      public java.lang.String getAudioPath() {
        java.lang.Object ref = audioPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          audioPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 音频路径 
       * </pre>
       *
       * <code>string AudioPath = 9;</code>
       * @return The bytes for audioPath.
       */
      public com.google.protobuf.ByteString
          getAudioPathBytes() {
        java.lang.Object ref = audioPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          audioPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 音频路径 
       * </pre>
       *
       * <code>string AudioPath = 9;</code>
       * @param value The audioPath to set.
       * @return This builder for chaining.
       */
      public Builder setAudioPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        audioPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 音频路径 
       * </pre>
       *
       * <code>string AudioPath = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAudioPath() {
        
        audioPath_ = getDefaultInstance().getAudioPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 音频路径 
       * </pre>
       *
       * <code>string AudioPath = 9;</code>
       * @param value The bytes for audioPath to set.
       * @return This builder for chaining.
       */
      public Builder setAudioPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        audioPath_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DongciDaci.SkEftBaseCfg)
    }

    // @@protoc_insertion_point(class_scope:DongciDaci.SkEftBaseCfg)
    private static final com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg();
    }

    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SkEftBaseCfg>
        PARSER = new com.google.protobuf.AbstractParser<SkEftBaseCfg>() {
      @java.lang.Override
      public SkEftBaseCfg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkEftBaseCfg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SkEftBaseCfg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SkEftBaseCfg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SkillEffectCfg_DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DongciDaci.SkillEffectCfg_Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */
    int getSkEftBaseCfgItemsCount();
    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */
    boolean containsSkEftBaseCfgItems(
        int key);
    /**
     * Use {@link #getSkEftBaseCfgItemsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>
    getSkEftBaseCfgItems();
    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */
    java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>
    getSkEftBaseCfgItemsMap();
    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */

    com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getSkEftBaseCfgItemsOrDefault(
        int key,
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg defaultValue);
    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */

    com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getSkEftBaseCfgItemsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code DongciDaci.SkillEffectCfg_Data}
   */
  public static final class SkillEffectCfg_Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DongciDaci.SkillEffectCfg_Data)
      SkillEffectCfg_DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SkillEffectCfg_Data.newBuilder() to construct.
    private SkillEffectCfg_Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SkillEffectCfg_Data() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SkillEffectCfg_Data();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SkillEffectCfg_Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                skEftBaseCfgItems_ = com.google.protobuf.MapField.newMapField(
                    SkEftBaseCfgItemsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>
              skEftBaseCfgItems__ = input.readMessage(
                  SkEftBaseCfgItemsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              skEftBaseCfgItems_.getMutableMap().put(
                  skEftBaseCfgItems__.getKey(), skEftBaseCfgItems__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkillEffectCfg_Data_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetSkEftBaseCfgItems();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkillEffectCfg_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data.class, com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data.Builder.class);
    }

    public static final int SKEFTBASECFG_ITEMS_FIELD_NUMBER = 1;
    private static final class SkEftBaseCfgItemsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>newDefaultInstance(
                  com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkillEffectCfg_Data_SkEftBaseCfgItemsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> skEftBaseCfgItems_;
    private com.google.protobuf.MapField<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>
    internalGetSkEftBaseCfgItems() {
      if (skEftBaseCfgItems_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SkEftBaseCfgItemsDefaultEntryHolder.defaultEntry);
      }
      return skEftBaseCfgItems_;
    }

    public int getSkEftBaseCfgItemsCount() {
      return internalGetSkEftBaseCfgItems().getMap().size();
    }
    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */

    @java.lang.Override
    public boolean containsSkEftBaseCfgItems(
        int key) {
      
      return internalGetSkEftBaseCfgItems().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSkEftBaseCfgItemsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> getSkEftBaseCfgItems() {
      return getSkEftBaseCfgItemsMap();
    }
    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> getSkEftBaseCfgItemsMap() {
      return internalGetSkEftBaseCfgItems().getMap();
    }
    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */
    @java.lang.Override

    public com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getSkEftBaseCfgItemsOrDefault(
        int key,
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg defaultValue) {
      
      java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> map =
          internalGetSkEftBaseCfgItems().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
     */
    @java.lang.Override

    public com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getSkEftBaseCfgItemsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> map =
          internalGetSkEftBaseCfgItems().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetSkEftBaseCfgItems(),
          SkEftBaseCfgItemsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> entry
           : internalGetSkEftBaseCfgItems().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>
        skEftBaseCfgItems__ = SkEftBaseCfgItemsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, skEftBaseCfgItems__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data)) {
        return super.equals(obj);
      }
      com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data other = (com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data) obj;

      if (!internalGetSkEftBaseCfgItems().equals(
          other.internalGetSkEftBaseCfgItems())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetSkEftBaseCfgItems().getMap().isEmpty()) {
        hash = (37 * hash) + SKEFTBASECFG_ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSkEftBaseCfgItems().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DongciDaci.SkillEffectCfg_Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DongciDaci.SkillEffectCfg_Data)
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkillEffectCfg_Data_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetSkEftBaseCfgItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableSkEftBaseCfgItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkillEffectCfg_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data.class, com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data.Builder.class);
      }

      // Construct using com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableSkEftBaseCfgItems().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trinitigames.server.conf.auto.SkillEffectCfg.internal_static_DongciDaci_SkillEffectCfg_Data_descriptor;
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data getDefaultInstanceForType() {
        return com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data.getDefaultInstance();
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data build() {
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data buildPartial() {
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data result = new com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data(this);
        int from_bitField0_ = bitField0_;
        result.skEftBaseCfgItems_ = internalGetSkEftBaseCfgItems();
        result.skEftBaseCfgItems_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data) {
          return mergeFrom((com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data other) {
        if (other == com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data.getDefaultInstance()) return this;
        internalGetMutableSkEftBaseCfgItems().mergeFrom(
            other.internalGetSkEftBaseCfgItems());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> skEftBaseCfgItems_;
      private com.google.protobuf.MapField<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>
      internalGetSkEftBaseCfgItems() {
        if (skEftBaseCfgItems_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SkEftBaseCfgItemsDefaultEntryHolder.defaultEntry);
        }
        return skEftBaseCfgItems_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>
      internalGetMutableSkEftBaseCfgItems() {
        onChanged();;
        if (skEftBaseCfgItems_ == null) {
          skEftBaseCfgItems_ = com.google.protobuf.MapField.newMapField(
              SkEftBaseCfgItemsDefaultEntryHolder.defaultEntry);
        }
        if (!skEftBaseCfgItems_.isMutable()) {
          skEftBaseCfgItems_ = skEftBaseCfgItems_.copy();
        }
        return skEftBaseCfgItems_;
      }

      public int getSkEftBaseCfgItemsCount() {
        return internalGetSkEftBaseCfgItems().getMap().size();
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
       */

      @java.lang.Override
      public boolean containsSkEftBaseCfgItems(
          int key) {
        
        return internalGetSkEftBaseCfgItems().getMap().containsKey(key);
      }
      /**
       * Use {@link #getSkEftBaseCfgItemsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> getSkEftBaseCfgItems() {
        return getSkEftBaseCfgItemsMap();
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> getSkEftBaseCfgItemsMap() {
        return internalGetSkEftBaseCfgItems().getMap();
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
       */
      @java.lang.Override

      public com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getSkEftBaseCfgItemsOrDefault(
          int key,
          com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg defaultValue) {
        
        java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> map =
            internalGetSkEftBaseCfgItems().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
       */
      @java.lang.Override

      public com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg getSkEftBaseCfgItemsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> map =
            internalGetSkEftBaseCfgItems().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearSkEftBaseCfgItems() {
        internalGetMutableSkEftBaseCfgItems().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
       */

      public Builder removeSkEftBaseCfgItems(
          int key) {
        
        internalGetMutableSkEftBaseCfgItems().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg>
      getMutableSkEftBaseCfgItems() {
        return internalGetMutableSkEftBaseCfgItems().getMutableMap();
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
       */
      public Builder putSkEftBaseCfgItems(
          int key,
          com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableSkEftBaseCfgItems().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;uint32, .DongciDaci.SkEftBaseCfg&gt; SkEftBaseCfg_items = 1;</code>
       */

      public Builder putAllSkEftBaseCfgItems(
          java.util.Map<java.lang.Integer, com.trinitigames.server.conf.auto.SkillEffectCfg.SkEftBaseCfg> values) {
        internalGetMutableSkEftBaseCfgItems().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DongciDaci.SkillEffectCfg_Data)
    }

    // @@protoc_insertion_point(class_scope:DongciDaci.SkillEffectCfg_Data)
    private static final com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data();
    }

    public static com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SkillEffectCfg_Data>
        PARSER = new com.google.protobuf.AbstractParser<SkillEffectCfg_Data>() {
      @java.lang.Override
      public SkillEffectCfg_Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkillEffectCfg_Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SkillEffectCfg_Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SkillEffectCfg_Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.trinitigames.server.conf.auto.SkillEffectCfg.SkillEffectCfg_Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DongciDaci_SkEftBaseCfg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DongciDaci_SkEftBaseCfg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DongciDaci_SkillEffectCfg_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DongciDaci_SkillEffectCfg_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DongciDaci_SkillEffectCfg_Data_SkEftBaseCfgItemsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DongciDaci_SkillEffectCfg_Data_SkEftBaseCfgItemsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SkillEffectCfg.proto\022\nDongciDaci\"\257\001\n\014S" +
      "kEftBaseCfg\022\n\n\002ID\030\001 \001(\r\022\016\n\006ChName\030\002 \001(\t\022" +
      "\016\n\006EnName\030\003 \001(\t\022\021\n\tClassName\030\004 \001(\t\022\021\n\tCh" +
      "Descrip\030\005 \001(\t\022\021\n\tEnDescrip\030\006 \001(\t\022\020\n\010Icon" +
      "Path\030\007 \001(\t\022\025\n\rVFXPrefabPath\030\010 \001(\t\022\021\n\tAud" +
      "ioPath\030\t \001(\t\"\275\001\n\023SkillEffectCfg_Data\022R\n\022" +
      "SkEftBaseCfg_items\030\001 \003(\01326.DongciDaci.Sk" +
      "illEffectCfg_Data.SkEftBaseCfgItemsEntry" +
      "\032R\n\026SkEftBaseCfgItemsEntry\022\013\n\003key\030\001 \001(\r\022" +
      "\'\n\005value\030\002 \001(\0132\030.DongciDaci.SkEftBaseCfg" +
      ":\0028\001B#\n!com.trinitigames.server.conf.aut" +
      "ob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DongciDaci_SkEftBaseCfg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DongciDaci_SkEftBaseCfg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DongciDaci_SkEftBaseCfg_descriptor,
        new java.lang.String[] { "ID", "ChName", "EnName", "ClassName", "ChDescrip", "EnDescrip", "IconPath", "VFXPrefabPath", "AudioPath", });
    internal_static_DongciDaci_SkillEffectCfg_Data_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DongciDaci_SkillEffectCfg_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DongciDaci_SkillEffectCfg_Data_descriptor,
        new java.lang.String[] { "SkEftBaseCfgItems", });
    internal_static_DongciDaci_SkillEffectCfg_Data_SkEftBaseCfgItemsEntry_descriptor =
      internal_static_DongciDaci_SkillEffectCfg_Data_descriptor.getNestedTypes().get(0);
    internal_static_DongciDaci_SkillEffectCfg_Data_SkEftBaseCfgItemsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DongciDaci_SkillEffectCfg_Data_SkEftBaseCfgItemsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
